"use client";
import {useMemo,useState} from "react";
type Hub={id:string;label:string;sub:string;x:number;y:number;color:string;url:string;links:string[]};
const hubs:Hub[]=[
{id:"hermes",label:"HERMES",sub:"Second Brain",x:500,y:350,color:"#61d7ff",url:"/connect",links:["projects","clients","revenue","marketing","trading","infrastructure","devices","files","agents"]},
{id:"projects",label:"PROJECTS",sub:"Kanban & delivery",x:255,y:115,color:"#ffd46b",url:"/projects",links:[]},
{id:"clients",label:"CLIENTS",sub:"CRM & support",x:515,y:90,color:"#63ffab",url:"/projects",links:[]},
{id:"revenue",label:"REVENUE",sub:"Finance & billing",x:805,y:150,color:"#58b5ff",url:"/projects",links:[]},
{id:"marketing",label:"MARKETING",sub:"Campaigns",x:850,y:370,color:"#ff7389",url:"/projects",links:[]},
{id:"trading",label:"TRADING",sub:"Market operations",x:755,y:585,color:"#ffc46a",url:"/projects",links:[]},
{id:"infrastructure",label:"INFRA",sub:"Deployments",x:520,y:635,color:"#b389ff",url:"/connect",links:[]},
{id:"devices",label:"DEVICES",sub:"Fleet & edge",x:290,y:570,color:"#63ffab",url:"/connect",links:[]},
{id:"files",label:"FILES",sub:"Central file share",x:125,y:365,color:"#5fb7ff",url:"/projects",links:[]},
{id:"agents",label:"AI AGENTS",sub:"Git Assassin",x:180,y:195,color:"#d48aff",url:"/git-assassin",links:[]}
];
const services=[["Project Board","/projects"],["Central File Share","/projects"],["Git Assassin","/git-assassin"],["Second Brain","/connect"]];
export default function LivingHive(){
const [selected,setSelected]=useState("hermes"),[paused,setPaused]=useState(false),[zoom,setZoom]=useState(1),[showLines,setShowLines]=useState(true),[mode,setMode]=useState("All"),[drag,setDrag]=useState<{x:number;y:number}|null>(null),[offset,setOffset]=useState({x:0,y:0});
const current=hubs.find(x=>x.id===selected)||hubs[0];
const visible=useMemo(()=>mode==="All"?hubs:mode==="Business"?hubs.filter(x=>["hermes","projects","clients","revenue","marketing"].includes(x.id)):hubs.filter(x=>["hermes","agents","files","devices","infrastructure","trading"].includes(x.id)),[mode]);
const edges=visible.filter(x=>x.id!=="hermes").map(x=>({a:hubs[0],b:x}));
return <main style={{minHeight:"100vh",background:"radial-gradient(ellipse at 50% 30%,#0d2450 0%,#050d20 60%,#030713 100%)",color:"#eaf4ff",fontFamily:"system-ui",padding:"clamp(14px,2.5vw,34px)"}}>
<style>{`@keyframes hivePulse{0%,100%{opacity:.65;filter:drop-shadow(0 0 8px currentColor)}50%{opacity:1;filter:drop-shadow(0 0 20px currentColor)}}@keyframes hiveFlow{to{stroke-dashoffset:-44}}@keyframes hiveOrbit{to{transform:rotate(360deg)}}.hive-flow{stroke-dasharray:8 13;animation:hiveFlow 2s linear infinite}.hive-pulse{animation:hivePulse 3s ease-in-out infinite}.hive-stop *{animation-play-state:paused!important}.hive-btn{cursor:pointer;background:#102943;color:#dcefff;border:1px solid #2c5980;border-radius:9px;padding:9px 13px}.hive-btn:focus-visible{outline:2px solid #72ffb4}.hive-panel{background:#091a32;border:1px solid #285078;border-radius:14px;padding:17px}@media(prefers-reduced-motion:reduce){.hive-flow,.hive-pulse{animation:none!important}}`}</style>
<header style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:16,borderBottom:"1px solid #234466",paddingBottom:18}}><div><div style={{fontSize:12,letterSpacing:3,color:"#78ffb7"}}>WISE² · LIVING HIVE</div><h1 style={{fontSize:"clamp(28px,4vw,48px)",margin:"6px 0"}}>CONNECT <span style={{color:"#71cfff"}}>NEURAL COMMAND</span></h1><p style={{color:"#9fb8d3",margin:0}}>One Mind · Many Machines · Interactive operations map</p></div><a href="/connect" style={{color:"#85d9ff"}}>← Connect overview</a></header>
<div style={{display:"flex",flexWrap:"wrap",gap:9,alignItems:"center",margin:"18px 0"}}><button className="hive-btn" onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?"▶ Resume motion":"Ⅱ Pause motion"}</button><button className="hive-btn" onClick={()=>setZoom(z=>Math.min(1.7,+(z+.15).toFixed(2)))}>＋ Zoom</button><button className="hive-btn" onClick={()=>setZoom(z=>Math.max(.65,+(z-.15).toFixed(2)))}>－ Zoom</button><button className="hive-btn" onClick={()=>{setZoom(1);setOffset({x:0,y:0})}}>Reset view</button><button className="hive-btn" onClick={()=>setShowLines(!showLines)} aria-pressed={showLines}>{showLines?"Hide links":"Show links"}</button><select aria-label="Network filter" value={mode} onChange={e=>setMode(e.target.value)} style={{background:"#102943",color:"#eaf4ff",border:"1px solid #2c5980",padding:10,borderRadius:9}}><option>All</option><option>Business</option><option>Technology</option></select><span style={{fontSize:12,color:"#ffc879"}}>Illustrative network · Telemetry unverified</span></div>
<div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(250px,300px)",gap:15,alignItems:"start"}}>
<section className="hive-panel" style={{overflow:"hidden",padding:0,position:"relative"}} aria-label="Interactive WISE² neural graph">
<svg className={paused?"hive-stop":""} viewBox="0 0 1000 720" role="img" aria-label="Hermes connected to business and technology departments" style={{width:"100%",height:"auto",touchAction:"none",cursor:drag?"grabbing":"grab"}} onPointerDown={e=>{if((e.target as Element).closest("[data-hub]"))return;setDrag({x:e.clientX-offset.x,y:e.clientY-offset.y});e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag)setOffset({x:e.clientX-drag.x,y:e.clientY-drag.y})}} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)}>
<defs><radialGradient id="bg"><stop stopColor="#143364"/><stop offset="1" stopColor="#050e22"/></radialGradient><filter id="blur"><feGaussianBlur stdDeviation="7"/></filter></defs><rect width="1000" height="720" fill="url(#bg)"/>{Array.from({length:80},(_,i)=><circle key={i} cx={(i*137+59)%1000} cy={(i*233+31)%720} r={i%5===0?1.5:.7} fill="#4d9ce3" opacity=".35"/>)}<g transform={`translate(${offset.x} ${offset.y}) translate(500 360) scale(${zoom}) translate(-500 -360)`}>
{showLines&&edges.map(({a,b})=><g key={b.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={b.color} strokeWidth="8" opacity=".14" filter="url(#blur)"/><line className="hive-flow" x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={b.color} strokeWidth="2.5" opacity=".9"/></g>)}
{visible.map(n=><g key={n.id} data-hub="true" tabIndex={0} role="button" aria-label={"Select "+n.label} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(n.id)}}} style={{cursor:"pointer",outline:"none"}}><circle className={paused?"":"hive-pulse"} cx={n.x} cy={n.y} r={n.id==="hermes"?83:60} fill={n.color} opacity=".12"/><circle cx={n.x} cy={n.y} r={n.id==="hermes"?72:50} fill="#091b33" stroke={n.color} strokeWidth={selected===n.id?5:2.5}/><circle cx={n.x} cy={n.y} r={n.id==="hermes"?62:43} fill="none" stroke={n.color} strokeDasharray="3 10" opacity=".5"/><text x={n.x} y={n.y-4} textAnchor="middle" fontSize={n.id==="hermes"?24:15} fontWeight="bold" fill="#f5fbff">{n.label}</text><text x={n.x} y={n.y+20} textAnchor="middle" fontSize="11" fill={n.color}>{n.sub}</text></g>)}</g></svg>
<div style={{padding:"8px 16px 15px",color:"#9eb7d3",fontSize:12}}>Select a node to inspect it. Drag empty space to pan. Use zoom controls to navigate.</div></section>
<aside className="hive-panel"><div style={{fontSize:12,letterSpacing:2,color:current.color}}>SELECTED NODE</div><h2>{current.label}</h2><p style={{color:"#b0c7db"}}>{current.sub}</p><div style={{padding:12,background:"#102843",borderRadius:10,marginBottom:14}}><span style={{color:"#ffc879"}}>● Not verified live</span><p style={{fontSize:12,color:"#9eb6ca"}}>No real-time device, financial or agent status is inferred.</p></div><a href={current.url} style={{display:"block",background:"#155069",padding:12,borderRadius:10,textAlign:"center",color:"#fff",textDecoration:"none"}}>Open {current.label} workspace ↗</a><h3 style={{marginTop:25}}>Quick navigation</h3>{services.map(([label,url])=><a key={label} href={url} style={{display:"block",padding:"12px 4px",borderBottom:"1px solid #25415e",color:"#85d9ff"}}>{label} ↗</a>)}</aside></div>
<footer style={{fontSize:12,color:"#8ba8c4",marginTop:16}}>Animated architecture preview · Respect reduced-motion settings · Protected production · Backend status integration pending</footer></main>
}