'use client';

import { useEffect, useState } from 'react';

interface AnimatedGuideProps {
  animation?: 'idle' | 'typing' | 'thinking';
  width?: number;
  height?: number;
}

/**
 * Animated guide character for studio workspace
 * Placeholder until Kling generates real sprite sheet
 */
export default function AnimatedGuide({
  animation = 'idle',
  width = 150,
  height = 150,
}: AnimatedGuideProps) {
  const [keyframes, setKeyframes] = useState('');

  useEffect(() => {
    // Generate CSS keyframes for sprite animation
    // When sprite sheet is available, update spriteUrl and frameCount
    const css = `
      @keyframes guide-idle {
        0% { transform: translateY(0px); }
        50% { transform: translateY(-5px); }
        100% { transform: translateY(0px); }
      }

      @keyframes guide-typing {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.8; }
      }

      @keyframes guide-thinking {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
      }
    `;
    setKeyframes(css);
  }, []);

  const animationName = {
    idle: 'guide-idle 3s ease-in-out infinite',
    typing: 'guide-typing 0.4s ease-in-out infinite',
    thinking: 'guide-thinking 2s linear infinite',
  }[animation];

  return (
    <>
      <style>{keyframes}</style>
      <div
        className="flex items-center justify-center bg-wise-surface rounded-lg p-4 border border-wise-medium"
        style={{
          width: `${width}px`,
          height: `${height}px`,
          animation: animationName,
        }}
      >
        {/* Placeholder emoji - replace with sprite sheet when available */}
        <div className="text-6xl">🦊</div>
      </div>
    </>
  );
}

/**
 * Example sprite sheet metadata (generated by Kling)
 * Update this when sprite sheet is ready
 */
export const GUIDE_SPRITE_CONFIG = {
  idle: {
    spriteUrl: '/animations/guide-idle-sprite.png',
    frameCount: 24,
    frameWidth: 150,
    frameHeight: 150,
    fps: 12,
  },
  typing: {
    spriteUrl: '/animations/guide-typing-sprite.png',
    frameCount: 20,
    frameWidth: 150,
    frameHeight: 150,
    fps: 15,
  },
  thinking: {
    spriteUrl: '/animations/guide-thinking-sprite.png',
    frameCount: 16,
    frameWidth: 150,
    frameHeight: 150,
    fps: 10,
  },
};
