[general]
static=yes
writeprotect=no
autofallthrough=yes

[inbound-calls]
exten => +18668343330,1,NoOp(WISE2 inbound Twilio call from ${CALLERID(num)})
 same => n,Answer()
 same => n,Set(CHANNEL(language)=en)
 same => n,Stasis(wise2-phone-app)
 same => n,Hangup()

exten => _.,1,NoOp(Unexpected Twilio destination ${EXTEN})
 same => n,Playback(silence/1)
 same => n,Hangup()

[wise2-phone]
exten => 1000,1,NoOp(Test extension)
 same => n,Playback(silence/1)
 same => n,Hangup()

[outbound-to-twilio]
exten => _+X.,1,Dial(PJSIP/${EXTEN}@twilio-endpoint,60)
 same => n,Hangup()
