; WISE2 Asterisk 20 / Twilio Elastic SIP Trunking

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=173.208.147.165
external_signaling_address=173.208.147.165

[twilio-aor]
type=aor
contact=sip:wise2-asterisk.pstn.ashburn.twilio.com:5060
qualify_frequency=60

[twilio-endpoint]
type=endpoint
transport=transport-udp
aors=twilio-aor
context=inbound-calls
disallow=all
allow=ulaw
allow=alaw
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
from_domain=wise2-asterisk.pstn.twilio.com

[twilio-identify]
type=identify
endpoint=twilio-endpoint
match=54.172.60.0/30
match=54.244.51.0/30

[wise2-gateway]
type=endpoint
transport=transport-udp
context=wise2-phone
auth=gateway-auth
aors=gateway-aor
disallow=all
allow=ulaw
allow=alaw
allow=opus

[gateway-auth]
type=auth
auth_type=userpass
username=wise2_gateway
password=ASTERISK_GATEWAY_SECRET

[gateway-aor]
type=aor
max_contacts=1
contact=sip:phone-gateway:5061
