import React from "react";

export default function BuildPreview({ hybrid, slots, dnaControls, prompt, onPromptChange, onBack, onSave, onGenerate, onCopy, saved }) {
  return <section className="rounded-[2rem] border border-zinc-800 bg-zinc-950 p-5 sm:p-8">
    <div className="grid gap-6 xl:grid-cols-[1fr_330px]">
      <div><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">Step 04 · Inspection Platform</div><h2 className="mt-3 text-4xl font-black uppercase sm:text-6xl">Preview Your Build</h2><p className="mt-3 text-sm font-bold uppercase tracking-wider text-zinc-500">This is what your production blueprint contains before generation.</p></div>
      <aside className={`rounded-2xl border p-5 ${hybrid.valid ? "border-emerald-500/30 bg-emerald-950/10" : "border-red-500/30 bg-red-950/10"}`}><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">// Foreman Inspection</div><div className="mt-3 text-xl font-black italic">“{hybrid.valid ? "That’s a clean build. Details lookin’ solid. Let’s lock it in." : "Measurements are off. Get that mix back to 100%."}”</div><div className={`mt-4 text-xs font-black uppercase ${hybrid.valid ? "text-emerald-400" : "text-red-400"}`}>{hybrid.valid ? "✓ Approved by the Foreman" : "× Correction required"}</div></aside>
    </div>
    <div className="mt-7 grid gap-5 lg:grid-cols-[1.35fr_1fr]">
      <section className="wt-panel rounded-3xl border border-zinc-800 bg-black/50 p-5"><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">// Output Blueprint Preview</div><h3 className="mt-4 text-2xl font-black uppercase">{hybrid.name}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{hybrid.description}</p><textarea aria-label="Editable blueprint prompt" value={prompt} onChange={(event) => onPromptChange(event.target.value)} className="mt-5 h-96 w-full rounded-2xl border border-zinc-800 bg-zinc-950 p-4 text-xs leading-5 text-zinc-300" /></section>
      <div className="space-y-5"><section className="wt-panel rounded-3xl border border-zinc-800 bg-black/50 p-5"><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">// Mix Recap</div><div className="mt-5 space-y-3">{slots.filter((slot) => slot.weight > 0).map((slot, index) => <div key={`${slot.source.id}:${index}`}><div className="flex justify-between text-xs font-black uppercase"><span>{String(index + 1).padStart(2, "0")} · {slot.source.name}</span><span className="text-orange-400">{slot.weight}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-900"><div className="h-full bg-orange-500" style={{ width: `${slot.weight}%` }} /></div></div>)}</div><div className="mt-5 flex justify-between border-t border-zinc-800 pt-4 text-sm font-black uppercase"><span>Total Influence</span><span className={hybrid.valid ? "text-emerald-400" : "text-red-400"}>{hybrid.totalWeight}%</span></div></section>
        <section className="wt-panel rounded-3xl border border-zinc-800 bg-black/50 p-5"><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">// DNA Specifications</div><dl className="mt-4 space-y-2">{Object.entries(dnaControls).map(([key, value]) => <div key={key} className="flex justify-between gap-4 border-b border-zinc-900 pb-2 text-xs"><dt className="font-black uppercase text-zinc-600">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="text-right font-bold text-zinc-300">{value}{key === "blendStrength" ? "%" : ""}</dd></div>)}</dl></section></div>
    </div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><button type="button" onClick={onBack} className="rounded-2xl border border-zinc-700 py-4 font-black uppercase text-zinc-300">← Adjust Mix</button><button type="button" onClick={onCopy} disabled={!prompt.trim()} className="rounded-2xl border border-orange-500/40 py-4 font-black uppercase text-orange-300">Copy Blueprint</button><button type="button" onClick={onSave} disabled={!hybrid.valid || !prompt.trim()} className="rounded-2xl border border-orange-500/40 py-4 font-black uppercase text-orange-300">{saved ? "★ Blueprint Filed" : "☆ Save Blueprint"}</button><button type="button" onClick={onGenerate} disabled={!hybrid.valid || !prompt.trim()} className="rounded-2xl bg-orange-500 py-4 font-black uppercase text-black disabled:bg-zinc-800 disabled:text-zinc-500">Generate Masterpiece →</button></div>
  </section>;
}
