import React, { useEffect, useState } from "react";
import { Accessibility, Archive, CircleUserRound, Database, LogOut, Save, Settings2, ShieldCheck } from "lucide-react";
import { DEFAULT_PREFERENCES, PREFERENCES_KEY, applyPreferences, normalizePreferences } from "./preferences.js";

function loadPreferences() {
  try { return normalizePreferences(JSON.parse(window.localStorage.getItem(PREFERENCES_KEY) || "{}")); }
  catch { return { ...DEFAULT_PREFERENCES }; }
}

export default function AccountCenter({ user, authStatus, favoriteCount, assetCount, blueprintCount, onSignOut, onOpen }) {
  const [preferences, setPreferences] = useState(loadPreferences);
  const [saveMessage, setSaveMessage] = useState("");
  useEffect(() => { applyPreferences(preferences, document.documentElement); }, []);
  const save = () => {
    const next = applyPreferences(preferences, document.documentElement);
    window.localStorage.setItem(PREFERENCES_KEY, JSON.stringify(next));
    setSaveMessage("Workspace preferences saved on this device.");
  };
  const reset = () => { const next = { ...DEFAULT_PREFERENCES }; setPreferences(next); applyPreferences(next, document.documentElement); window.localStorage.setItem(PREFERENCES_KEY, JSON.stringify(next)); setSaveMessage("Workspace defaults restored."); };

  return <section className="overflow-hidden rounded-[2rem] border border-orange-500/30 bg-zinc-950">
    <header className="border-b border-orange-500/20 bg-gradient-to-r from-orange-950/60 via-zinc-950 to-black p-5 sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_20rem] lg:items-end"><div><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">Build District 02 · Crew Office</div><h2 className="mt-3 text-4xl font-black uppercase sm:text-5xl">Account // Settings</h2><p className="mt-3 text-sm font-bold uppercase tracking-wider text-zinc-400">Identity, synchronization, workspace controls, and data status.</p></div><aside className="rounded-2xl border border-orange-500/30 bg-black/60 p-4"><div className="text-[10px] font-black uppercase tracking-[0.25em] text-orange-400">Foreman Office Note</div><p className="mt-2 text-sm font-bold text-zinc-200">“Keep your tools labeled and your blueprints backed up. Saves everybody a headache.”</p></aside></div></header>

    <div className="grid gap-6 p-5 lg:grid-cols-[22rem_1fr] sm:p-8">
      <aside className="space-y-4"><section className="rounded-2xl border border-zinc-800 bg-black/50 p-5"><div className="flex items-center gap-3"><div className="rounded-full bg-orange-500 p-3 text-black"><CircleUserRound size={25}/></div><div><div className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Crew Identity</div><div className="mt-1 font-black">{user?.displayName || "Local Builder"}</div></div></div>{user ? <><div className="mt-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3"><div className="text-xs font-black text-emerald-300">● Account synchronized</div><div className="mt-1 break-all text-xs text-zinc-400">{user.email}</div></div><button type="button" onClick={onSignOut} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-zinc-700 py-3 text-xs font-black uppercase text-zinc-300"><LogOut size={15}/> Sign Out</button></>:<div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-xs font-bold leading-5 text-amber-300">Local mode is active. Use the account panel above to sign in or register and synchronize supported project data.</div>}</section>
        <section className="rounded-2xl border border-zinc-800 bg-black/50 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-orange-400"><Database size={16}/> Workspace Inventory</div><div className="mt-4 grid grid-cols-3 gap-2 text-center">{[[favoriteCount,"Favorites"],[blueprintCount,"Blueprints"],[assetCount,"Builds"]].map(([value,label])=><button type="button" key={label} onClick={()=>onOpen(label === "Builds" ? "results" : label === "Blueprints" ? "blueprints" : "favorites")} className="rounded-xl border border-zinc-800 p-3"><div className="text-xl font-black text-orange-400">{value}</div><div className="mt-1 text-[9px] font-black uppercase text-zinc-600">{label}</div></button>)}</div></section>
        <section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-emerald-300"><ShieldCheck size={16}/> Security Posture</div><p className="mt-2 text-xs leading-5 text-zinc-400">Provider credentials remain server-side. Session cookies, password hashing, CSRF controls, and secure production configuration are built into the website.</p></section></aside>

      <main className="space-y-5"><section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.25em] text-orange-400"><Settings2 size={17}/> Workspace Preferences</div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-black uppercase text-zinc-500">Interface Density<select value={preferences.density} onChange={(event)=>setPreferences((current)=>({...current,density:event.target.value}))} className="mt-2 h-12 w-full rounded-xl border border-zinc-800 bg-black px-4 text-sm text-white"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="text-xs font-black uppercase text-zinc-500">Motion Preference<select value={preferences.motion} onChange={(event)=>setPreferences((current)=>({...current,motion:event.target.value}))} className="mt-2 h-12 w-full rounded-xl border border-zinc-800 bg-black px-4 text-sm text-white"><option value="system">Follow device setting</option><option value="reduced">Reduce decorative motion</option></select></label></div><div className="mt-5 grid gap-3 md:grid-cols-2"><label className="flex cursor-pointer items-center justify-between rounded-xl border border-zinc-800 p-4"><span><span className="block text-sm font-black">Prompt autosave</span><span className="mt-1 block text-xs text-zinc-500">Keep editable drafts available locally.</span></span><input aria-label="Prompt autosave" type="checkbox" checked={preferences.promptAutosave} onChange={(event)=>setPreferences((current)=>({...current,promptAutosave:event.target.checked}))} className="h-5 w-5 accent-orange-500"/></label><label className="flex cursor-pointer items-center justify-between rounded-xl border border-zinc-800 p-4"><span><span className="block text-sm font-black">Foreman guidance</span><span className="mt-1 block text-xs text-zinc-500">Show contextual build-floor advice.</span></span><input aria-label="Foreman guidance" type="checkbox" checked={preferences.foremanTips} onChange={(event)=>setPreferences((current)=>({...current,foremanTips:event.target.checked}))} className="h-5 w-5 accent-orange-500"/></label></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={reset} className="rounded-xl border border-zinc-700 py-3 text-xs font-black uppercase text-zinc-400">Restore Defaults</button><button type="button" onClick={save} className="flex items-center justify-center gap-2 rounded-xl bg-orange-500 py-3 text-xs font-black uppercase text-black"><Save size={16}/> Save Settings</button></div>{saveMessage && <div className="mt-3 text-sm font-bold text-emerald-300">{saveMessage}</div>}</section>

        <section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.25em] text-orange-400"><Accessibility size={17}/> Accessibility & Device</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-zinc-800 p-4"><div className="text-sm font-black">Keyboard navigation</div><p className="mt-2 text-xs leading-5 text-zinc-500">Visible focus states and semantic controls are enabled across the build floor.</p></div><div className="rounded-xl border border-zinc-800 p-4"><div className="text-sm font-black">Reduced motion</div><p className="mt-2 text-xs leading-5 text-zinc-500">Decorative Foreman animation stops when reduced motion is selected here or on the device.</p></div></div></section>

        <section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.25em] text-orange-400"><Archive size={17}/> Data & Integrations</div><div className="mt-4 grid gap-3 md:grid-cols-3">{[["Account sync",user?"Connected":"Local only"],["AI providers","Server managed"],["Commerce","Integration staged"]].map(([label,value])=><div key={label} className="rounded-xl border border-zinc-800 p-4"><div className="text-[10px] font-black uppercase text-zinc-600">{label}</div><div className="mt-2 text-sm font-black text-zinc-300">{value}</div></div>)}</div><p className="mt-4 text-xs leading-5 text-zinc-500">Profile editing, billing, team seats, and downloadable account archives remain explicit production integration boundaries; this screen does not fabricate those server operations.</p></section></main>
    </div>
  </section>;
}
