import React, { useEffect, useMemo, useState } from "react";
import { ImageIcon, ServerCog, Sparkles, Upload } from "lucide-react";
import { generateImage, getImageEntitlement, listImageProviders, openBillingPortal, startProCheckout, transformImage } from "./imageClient.js";

export default function ImageBuilder({ systems = [], initialPrompt = "", onCompleted }) {
  const [provider, setProvider] = useState(null);
  const [entitlement, setEntitlement] = useState({ plan:"free", active:false, watermarkRequired:true });
  const [sourceImage, setSourceImage] = useState(null);
  const [sourcePreview, setSourcePreview] = useState("");
  const [form, setForm] = useState({ prompt: initialPrompt, negativePrompt: "blurry, low quality, malformed anatomy, watermark", aspectRatio: "1:1", steps: 18, strength: 0.62 });
  const [state, setState] = useState({ status: "idle", message: "", result: null });
  const [billingMessage, setBillingMessage] = useState("");
  const presets = useMemo(() => systems.slice(0, 8).map((system) => ({ id: system.id, name: system.name, prompt: `Transform the uploaded photograph using ${system.name} visual DNA. ${system.vibe || system.description} Preserve the subject's recognizable identity, pose, clothing structure, and important facial features while applying the selected WISE TOUCH art direction.` })), [systems]);
  useEffect(() => { setForm((current) => ({ ...current, prompt: initialPrompt || current.prompt })); }, [initialPrompt]);
  useEffect(() => { listImageProviders().then((items) => setProvider(items[0])).catch((error) => setState({ status: "error", message: error.message, result: null })); }, []);
  useEffect(() => { getImageEntitlement().then(setEntitlement).catch(()=>{}); }, []);
  useEffect(() => { if (!sourceImage) { setSourcePreview(""); return undefined; } const url = URL.createObjectURL(sourceImage); setSourcePreview(url); return () => URL.revokeObjectURL(url); }, [sourceImage]);
  const submit = async (promptOverride) => {
    const prompt = typeof promptOverride === "string" ? promptOverride : form.prompt;
    if (!prompt.trim()) return;
    setForm((current) => ({ ...current, prompt }));
    setState({ status: "loading", message: sourceImage ? "Transforming your photo on the local build engine…" : "Creating your image on the local build engine…", result: null });
    try {
      const input = { ...form, prompt };
      const result = sourceImage ? await transformImage(sourceImage, input) : await generateImage(input);
      setState({ status: "success", message: result.watermarked ? "Built free with the official W² watermark and filed in My Builds." : "Built with your paid clean-download entitlement and filed in My Builds.", result });
      onCompleted?.(result, { ...input, sourceName: sourceImage?.name || null });
    } catch (error) { setState({ status: "error", message: error.message, result: null }); }
  };
  const billingAction = async () => { setBillingMessage("Opening secure billing…"); try { const url = entitlement.active ? await openBillingPortal() : await startProCheckout(); window.location.assign(url); } catch(error) { setBillingMessage(error.message); } };

  return <section className="overflow-hidden rounded-[2rem] border border-orange-500/30 bg-zinc-950"><header className="border-b border-orange-500/20 bg-gradient-to-r from-orange-950/60 via-zinc-950 to-black p-5 sm:p-8"><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">Build District 02 · On-Site Image Shop</div><h2 className="mt-3 text-4xl font-black uppercase sm:text-5xl">Upload. Choose. Generate.</h2><p className="mt-3 max-w-3xl text-sm font-bold uppercase tracking-wider text-zinc-400">Your photo goes in · WISE TOUCH art comes out · No outside website required</p></header>
    <div className="grid gap-6 p-5 xl:grid-cols-[1fr_22rem] sm:p-8"><main className="space-y-5"><section className="rounded-2xl border border-orange-500/20 bg-black/40 p-5"><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">01 // Upload Your Photo</div><label className="mt-4 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-zinc-700 bg-black/50 p-5 text-center hover:border-orange-500"><Upload className="text-orange-400"/><span className="mt-3 text-sm font-black">{sourceImage ? sourceImage.name : "Choose PNG, JPEG, or WebP"}</span><span className="mt-1 text-xs text-zinc-500">Maximum 10MB · processed inside WISE TOUCH</span><input aria-label="Upload source photo" type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(event) => setSourceImage(event.target.files?.[0] || null)}/></label>{sourcePreview && <img src={sourcePreview} alt="Uploaded source preview" className="mt-4 max-h-80 w-full rounded-2xl border border-zinc-800 object-contain"/>}</section>
      <section className="rounded-2xl border border-orange-500/20 bg-black/40 p-5"><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">02 // Choose Your WISE TOUCH Treatment</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{presets.map((preset) => <button type="button" key={preset.id} disabled={!provider?.configured || state.status === "loading"} onClick={() => submit(preset.prompt)} className="rounded-xl border border-zinc-800 bg-zinc-950 p-4 text-left transition hover:border-orange-500 disabled:opacity-40"><span className="text-[10px] font-black uppercase tracking-wider text-orange-400">Apply & Generate</span><span className="mt-2 block text-sm font-black uppercase">{preset.name}</span></button>)}</div>{!sourceImage && <p className="mt-3 text-xs font-bold text-amber-300">Upload a photo first to transform that exact image, or use a treatment for text-only generation.</p>}</section>
      <section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><label className="block text-sm font-bold text-zinc-300">Custom Production Prompt<textarea aria-label="Image production prompt" value={form.prompt} onChange={(event) => setForm((current) => ({ ...current, prompt: event.target.value }))} placeholder="Describe your custom WISE TOUCH transformation..." className="mt-2 h-40 w-full rounded-2xl border border-zinc-800 bg-black p-4 text-sm leading-6"/></label><details className="mt-4 rounded-xl border border-zinc-800 p-4"><summary className="cursor-pointer text-xs font-black uppercase text-zinc-400">Advanced image controls</summary><label className="mt-4 block text-sm font-bold text-zinc-300">Negative Prompt<textarea aria-label="Image negative prompt" value={form.negativePrompt} onChange={(event) => setForm((current) => ({ ...current, negativePrompt: event.target.value }))} className="mt-2 h-20 w-full rounded-xl border border-zinc-800 bg-black p-3 text-sm"/></label><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold text-zinc-400">Aspect Ratio<select value={form.aspectRatio} onChange={(event) => setForm((current) => ({ ...current, aspectRatio: event.target.value }))} className="mt-2 h-11 w-full rounded-xl border border-zinc-800 bg-black px-3"><option>1:1</option><option>16:9</option><option>9:16</option></select></label><label className="text-xs font-bold text-zinc-400">Quality Steps<input aria-label="Image quality steps" type="number" min="8" max="30" value={form.steps} onChange={(event) => setForm((current) => ({ ...current, steps: Number(event.target.value) }))} className="mt-2 h-11 w-full rounded-xl border border-zinc-800 bg-black px-3"/></label><label className="text-xs font-bold text-zinc-400">Photo Transformation<input aria-label="Photo transformation strength" type="range" min="0.15" max="0.9" step="0.01" value={form.strength} onChange={(event) => setForm((current) => ({ ...current, strength: Number(event.target.value) }))} className="mt-4 w-full accent-orange-500"/><span className="text-[10px] text-zinc-600">{Math.round(form.strength * 100)}%</span></label></div></details><button type="button" disabled={!form.prompt.trim() || !provider?.configured || state.status === "loading"} onClick={() => submit()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-orange-500 py-4 font-black uppercase text-black disabled:bg-zinc-800 disabled:text-zinc-500"><Sparkles size={18}/>{state.status === "loading" ? "Building Right Here…" : sourceImage ? "Transform Uploaded Photo" : "Generate Image Here"}</button></section>
      {state.message && <div className={`rounded-xl border p-4 text-sm font-bold ${state.status === "error" ? "border-red-500/30 text-red-300" : "border-emerald-500/30 text-emerald-300"}`}>{state.message}</div>}{state.result?.assetUrl && <section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><div className="text-xs font-black uppercase tracking-[0.25em] text-emerald-300">03 // Finished Build · Displayed Automatically</div><div className="mt-2 text-xs font-bold text-zinc-400">{state.result.watermarked?"Free delivery · Official W² watermark baked in":"Paid delivery · Clean authenticated original"}</div><img src={state.result.assetUrl} alt="Latest WISE TOUCH generated result" className="mt-4 w-full rounded-2xl border border-zinc-800"/><a href={state.result.assetUrl} download className="mt-4 block rounded-xl border border-emerald-500/40 py-3 text-center text-sm font-black uppercase text-emerald-300">Download Finished Image</a></section>}</main>
      <aside className="space-y-4"><section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase text-emerald-300"><ImageIcon size={17}/> Image Cost</div><div className="mt-3 text-3xl font-black">$0.00</div><p className="mt-2 text-xs leading-5 text-zinc-400">No per-image API fee. Server electricity and storage still apply.</p></section><section className={`rounded-2xl border p-5 ${entitlement.active?"border-emerald-500/30 bg-emerald-500/5":"border-orange-500/30 bg-orange-500/5"}`}><div className="text-xs font-black uppercase tracking-wider text-orange-400">Download Plan · {entitlement.active?"Pro":"Free"}</div><div className="mt-3 text-lg font-black">{entitlement.active?"Clean W²-free downloads":"Official W² watermark applied"}</div><p className="mt-2 text-xs leading-5 text-zinc-400">{entitlement.active?"Your active paid entitlement unlocks authenticated clean originals.":"Free generations display and download with the official W² brand watermark baked into the file."}</p>{entitlement.billingConfigured ? <button type="button" onClick={billingAction} className="mt-4 w-full rounded-xl bg-orange-500 py-3 text-xs font-black uppercase text-black">{entitlement.active?"Manage Billing":"Upgrade to Pro"}</button> : <div className="mt-4 rounded-xl border border-zinc-800 p-3 text-xs font-bold text-amber-300">Secure Pro checkout will appear after Stripe is configured by the site owner.</div>}{billingMessage && <div className="mt-3 text-xs font-bold text-zinc-400">{billingMessage}</div>}</section><section className="rounded-2xl border border-zinc-800 bg-black/50 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase text-orange-400"><ServerCog size={17}/> Private Local Engine</div><div className="mt-3 text-sm font-black">{provider?.name || "Checking service…"}</div><div className={`mt-2 text-xs font-bold ${provider?.configured ? "text-emerald-300" : "text-amber-300"}`}>{provider?.configured ? "● Ready inside WISE TOUCH" : "Setup required: LOCAL_IMAGE_API_URL"}</div><p className="mt-3 text-xs leading-5 text-zinc-500">Users never need to leave this website. Results display here automatically and are added to My Builds.</p></section></aside></div></section>;
}
