import React, { useState } from "react";
import { ArrowLeft, CreditCard, LockKeyhole, PackageCheck, ShieldCheck, ShoppingCart, Trash2 } from "lucide-react";
import { BLUEPRINTS, COMMERCE_STORAGE_KEY, PACKS, cartTotal, createCommerceState, toggleCommerceId, validateCheckout } from "./commerce.js";

function loadCart() {
  try { return createCommerceState(JSON.parse(window.localStorage.getItem(COMMERCE_STORAGE_KEY) || "{}")); }
  catch { return createCommerceState(); }
}

export default function CheckoutPanel({ user, onBack }) {
  const [commerce, setCommerce] = useState(loadCart);
  const [form, setForm] = useState({ email: user?.email || "", country: "", licenseAccepted: false });
  const [errors, setErrors] = useState([]);
  const [handoff, setHandoff] = useState("");
  const catalog = [...PACKS, ...BLUEPRINTS];
  const cart = catalog.filter((item) => commerce.cartIds.includes(item.id));
  const remove = (id) => setCommerce((current) => { const next = toggleCommerceId(current, "cartIds", id); window.localStorage.setItem(COMMERCE_STORAGE_KEY, JSON.stringify(next)); return next; });
  const continueToPayment = () => { const result = validateCheckout(form, commerce); setErrors(result.errors); setHandoff(result.valid ? "Order review passed. Secure payment is awaiting the production payment-provider connection; no charge or order was created." : ""); };

  return <section className="overflow-hidden rounded-[2rem] border border-orange-500/30 bg-zinc-950">
    <header className="border-b border-orange-500/20 bg-gradient-to-r from-orange-950/60 via-zinc-950 to-black p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">Build District 02 · Dispatch Office</div><h2 className="mt-3 text-4xl font-black uppercase sm:text-5xl">Secure Checkout</h2><p className="mt-3 text-sm font-bold uppercase tracking-wider text-zinc-400">Review inventory, delivery, licensing, and payment readiness.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-xs font-black uppercase text-emerald-300"><LockKeyhole size={16}/> Server-side payment handoff</div></div></header>
    <div className="grid gap-6 p-5 lg:grid-cols-[1fr_22rem] sm:p-8"><main className="space-y-5"><button type="button" onClick={onBack} className="flex items-center gap-2 text-xs font-black uppercase text-zinc-500 hover:text-orange-400"><ArrowLeft size={15}/> Continue shopping</button>
      <section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.22em] text-orange-400"><ShoppingCart size={17}/> Order Inventory</div>{cart.length ? <div className="mt-4 space-y-3">{cart.map((item)=><article key={item.id} className={`rounded-xl border border-zinc-800 bg-gradient-to-r ${item.accent} p-4`}><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase text-orange-400">{item.kind} · {item.category}</div><h3 className="mt-1 text-lg font-black uppercase">{item.name}</h3><div className="text-xs font-bold text-zinc-500">{item.subtitle} · {item.creator}</div><div className="mt-2 text-[11px] font-bold text-emerald-300">✓ Commercial license included</div></div><div className="text-right"><div className="text-xl font-black">${item.price.toFixed(2)}</div><button aria-label={`Remove ${item.name} from checkout`} onClick={()=>remove(item.id)} className="mt-3 inline-flex items-center gap-1 text-[10px] font-black uppercase text-red-400"><Trash2 size={13}/> Remove</button></div></div></article>)}</div>:<div className="mt-4 rounded-xl border border-zinc-800 p-6 text-sm text-zinc-500">Your cart is empty. Return to the Supply Depot or Marketplace to add inventory.</div>}</section>
      <section className="rounded-2xl border border-zinc-800 bg-black/40 p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.22em] text-orange-400"><PackageCheck size={17}/> Digital Delivery</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black uppercase text-zinc-500">Delivery Email<input aria-label="Delivery email" type="email" value={form.email} onChange={(event)=>setForm((current)=>({...current,email:event.target.value}))} placeholder="builder@example.com" className="mt-2 h-12 w-full rounded-xl border border-zinc-800 bg-black px-4 text-sm text-white"/></label><label className="text-xs font-black uppercase text-zinc-500">Billing Country or Region<select aria-label="Billing country or region" value={form.country} onChange={(event)=>setForm((current)=>({...current,country:event.target.value}))} className="mt-2 h-12 w-full rounded-xl border border-zinc-800 bg-black px-4 text-sm text-white"><option value="">Select region</option><option value="US">United States</option><option value="CA">Canada</option><option value="GB">United Kingdom</option><option value="EU">European Union</option><option value="OTHER">Other</option></select></label></div><label className="mt-5 flex cursor-pointer items-start gap-3 rounded-xl border border-zinc-800 p-4"><input aria-label="Accept digital product and license terms" type="checkbox" checked={form.licenseAccepted} onChange={(event)=>setForm((current)=>({...current,licenseAccepted:event.target.checked}))} className="mt-1 h-5 w-5 accent-orange-500"/><span><span className="block text-sm font-black">Digital product and commercial-license terms</span><span className="mt-1 block text-xs leading-5 text-zinc-500">I understand this cart contains instantly delivered digital products. Final legal terms must be linked before live sales are enabled.</span></span></label>{errors.length > 0 && <div className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm font-bold text-red-300">{errors.map((error)=><div key={error}>• {error}</div>)}</div>}</section></main>
      <aside className="self-start rounded-2xl border border-orange-500/30 bg-black/60 p-5 lg:sticky lg:top-5"><div className="text-xs font-black uppercase tracking-[0.22em] text-orange-400">Order Summary</div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between text-zinc-400"><span>Digital items</span><span>{cart.length}</span></div><div className="flex justify-between text-zinc-400"><span>Delivery</span><span>Instant</span></div><div className="flex justify-between text-zinc-400"><span>Estimated tax</span><span>At payment</span></div><div className="flex justify-between border-t border-zinc-800 pt-4 text-xl font-black"><span>Subtotal</span><span>${cartTotal(commerce).toFixed(2)}</span></div></div><button type="button" disabled={!cart.length} onClick={continueToPayment} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-orange-500 py-4 text-xs font-black uppercase text-black disabled:bg-zinc-800 disabled:text-zinc-600"><CreditCard size={17}/> Continue to Secure Payment</button>{handoff && <div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-xs font-bold leading-5 text-amber-300">{handoff}</div>}<div className="mt-5 flex items-start gap-2 text-xs font-bold leading-5 text-zinc-500"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-emerald-400"/>Card details will be collected only by a PCI-compliant hosted payment provider after it is connected.</div><p className="mt-5 border-t border-zinc-800 pt-4 text-[11px] leading-5 text-zinc-600">This website does not collect card data or fabricate completed orders while payment service credentials are absent.</p></aside></div>
  </section>;
}
