import React, { useMemo, useState } from "react";
import { Heart, PackageOpen, Search, ShoppingCart, Star, X } from "lucide-react";
import { BLUEPRINTS, COMMERCE_STORAGE_KEY, PACKS, cartTotal, createCommerceState, toggleCommerceId } from "./commerce.js";

function loadState() {
  try { return createCommerceState(JSON.parse(window.localStorage.getItem(COMMERCE_STORAGE_KEY) || "{}")); }
  catch { return createCommerceState(); }
}

export default function Storefront({ mode = "packs", onUseBlueprint, onCheckout }) {
  const catalog = mode === "packs" ? PACKS : BLUEPRINTS;
  const [commerce, setCommerce] = useState(loadState);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [selectedId, setSelectedId] = useState(catalog[0].id);
  const [checkoutNotice, setCheckoutNotice] = useState("");
  const allCatalog = [...PACKS, ...BLUEPRINTS];
  const selected = catalog.find((item) => item.id === selectedId) || catalog[0];
  const categories = ["All", ...new Set(catalog.map((item) => item.category))];
  const visible = useMemo(() => catalog.filter((item) => (category === "All" || item.category === category) && `${item.name} ${item.subtitle} ${item.category} ${item.creator}`.toLowerCase().includes(query.toLowerCase())), [catalog, category, query]);
  const cart = allCatalog.filter((item) => commerce.cartIds.includes(item.id));
  const update = (field, id) => setCommerce((current) => { const next = toggleCommerceId(current, field, id); window.localStorage.setItem(COMMERCE_STORAGE_KEY, JSON.stringify(next)); return next; });
  const title = mode === "packs" ? "Packs // Supply Depot" : "Blueprints // Master Your Vision";
  const subtitle = mode === "packs" ? "Fuel your creativity. Expand your arsenal." : "Professional-grade blueprints. Proven creative structures.";

  return <section className="overflow-hidden rounded-[2rem] border border-orange-500/30 bg-zinc-950">
    <header className="border-b border-orange-500/20 bg-gradient-to-r from-orange-950/60 via-zinc-950 to-black p-5 sm:p-8">
      <div className="grid gap-5 lg:grid-cols-[1fr_20rem] lg:items-end"><div><div className="text-xs font-black uppercase tracking-[0.3em] text-orange-400">Build District 02 · {mode === "packs" ? "Supply Depot" : "Blueprint Exchange"}</div><h2 className="mt-3 text-4xl font-black uppercase sm:text-5xl">{title}</h2><p className="mt-3 text-sm font-bold uppercase tracking-wider text-zinc-400">{subtitle}</p></div><aside className="rounded-2xl border border-orange-500/30 bg-black/60 p-4"><div className="text-[10px] font-black uppercase tracking-[0.25em] text-orange-400">Foreman Procurement Note</div><p className="mt-2 text-sm font-bold text-zinc-200">“Good tools make good builds. Legendary tools change the game.”</p></aside></div>
    </header>

    <div className="grid gap-6 p-5 xl:grid-cols-[13rem_1fr_19rem] sm:p-8">
      <aside className="space-y-4"><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">Browse Inventory</div><label className="block text-xs font-bold uppercase text-zinc-500">Search<div className="relative mt-2"><Search className="absolute left-3 top-3.5 text-zinc-600" size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-zinc-800 bg-black pl-10 pr-3 text-sm" placeholder="Search..."/></div></label><div className="space-y-2">{categories.map((item)=><button key={item} onClick={()=>setCategory(item)} className={`w-full rounded-xl border px-3 py-3 text-left text-xs font-black uppercase ${category === item ? "border-orange-500 bg-orange-500 text-black" : "border-zinc-800 bg-black/40 text-zinc-400"}`}>{item}</button>)}</div><div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-[11px] font-bold leading-5 text-emerald-300">Commercial-license details are shown per listing. Inventory and pricing are development seed data until the commerce backend is connected.</div></aside>

      <main><div className="mb-4 flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">Featured {mode === "packs" ? "Packs" : "Blueprints"}</div><div className="mt-1 text-xs text-zinc-500">{visible.length} listings available</div></div><div className="text-[10px] font-black uppercase tracking-wider text-zinc-600">Instant digital access</div></div>{visible.length ? <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{visible.map((item)=><article key={item.id} onClick={()=>setSelectedId(item.id)} className={`cursor-pointer overflow-hidden rounded-2xl border bg-gradient-to-br ${item.accent} ${selected.id === item.id ? "border-orange-500" : "border-zinc-800"}`}><div className="h-28 border-b border-white/5 p-4"><span className="rounded-md border border-orange-500/50 bg-black/60 px-2 py-1 text-[10px] font-black uppercase text-orange-300">{item.badge}</span><PackageOpen className="mt-5 text-orange-400" size={30}/></div><div className="p-4"><div className="text-lg font-black uppercase">{item.name}</div><div className="text-xs font-bold uppercase text-zinc-500">{item.subtitle}</div><div className="mt-3 flex items-center justify-between"><span className="text-xs font-black text-amber-400">★ {item.rating}</span><span className="text-xl font-black text-orange-500">${item.price.toFixed(2)}</span></div><div className="mt-3 flex gap-2"><button aria-label={`Add ${item.name} to wishlist`} onClick={(event)=>{event.stopPropagation();update("wishlistIds",item.id)}} className={`rounded-xl border p-3 ${commerce.wishlistIds.includes(item.id)?"border-pink-500 bg-pink-500/15 text-pink-300":"border-zinc-700 text-zinc-400"}`}><Heart size={17}/></button><button onClick={(event)=>{event.stopPropagation();update("cartIds",item.id)}} className={`flex-1 rounded-xl py-3 text-xs font-black uppercase ${commerce.cartIds.includes(item.id)?"border border-orange-500 text-orange-300":"bg-orange-500 text-black"}`}>{commerce.cartIds.includes(item.id)?"Remove from cart":"Add to cart"}</button></div></div></article>)}</div>:<div className="rounded-2xl border border-zinc-800 bg-black/40 p-8 text-sm text-zinc-400">No inventory matches those filters.</div>}
        <section className="mt-6 rounded-2xl border border-orange-500/20 bg-black/50 p-5"><div className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">Selected Listing</div><h3 className="mt-3 text-2xl font-black uppercase">{selected.name} · {selected.subtitle}</h3><p className="mt-2 text-sm text-zinc-500">Built by {selected.creator} · Versioned digital inventory with documented usage guidance.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{selected.contents.map((item)=><div key={item} className="rounded-lg border border-zinc-800 px-3 py-2 text-xs font-bold text-zinc-300">✓ {item}</div>)}</div>{mode === "blueprints" && <button type="button" onClick={()=>onUseBlueprint?.(selected)} className="mt-4 w-full rounded-xl border border-orange-500/50 py-3 text-xs font-black uppercase text-orange-300">Preview Blueprint in Builder</button>}</section>
      </main>

      <aside><section className="rounded-2xl border border-orange-500/30 bg-black/60 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-orange-400"><ShoppingCart size={16}/> Your Cart</div><span className="text-xs font-bold text-zinc-500">{cart.length} items</span></div><div className="mt-4 space-y-3">{cart.length ? cart.map((item)=><div key={item.id} className="flex items-start justify-between gap-2 border-b border-zinc-800 pb-3"><div><div className="text-xs font-black">{item.name}</div><div className="text-[10px] text-zinc-500">{item.subtitle}</div></div><div className="flex items-center gap-2"><span className="text-xs font-black">${item.price.toFixed(2)}</span><button aria-label={`Remove ${item.name} from cart`} onClick={()=>update("cartIds",item.id)} className="text-zinc-600 hover:text-red-400"><X size={14}/></button></div></div>):<div className="rounded-xl border border-zinc-800 p-4 text-xs text-zinc-500">Your supply cart is empty.</div>}</div><div className="mt-4 flex justify-between border-t border-zinc-800 pt-4 font-black"><span>Subtotal</span><span>${cartTotal(commerce).toFixed(2)}</span></div><button disabled={!cart.length} onClick={()=>onCheckout?.()} className="mt-4 w-full rounded-xl bg-orange-500 py-3 text-xs font-black uppercase text-black disabled:bg-zinc-800 disabled:text-zinc-600">Proceed to Checkout</button>{checkoutNotice && <div className="mt-3 text-xs font-bold leading-5 text-amber-300">{checkoutNotice}</div>}</section><section className="mt-4 rounded-2xl border border-orange-500/20 bg-gradient-to-br from-orange-950/50 to-black p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-orange-400"><Star size={15}/> WISE TOUCH Pro</div><p className="mt-3 text-xs leading-5 text-zinc-400">Member pricing, early drops, exclusive inventory, and priority support are ready for entitlement wiring.</p><button onClick={()=>setCheckoutNotice("Pro enrollment is staged until account billing is connected.")} className="mt-4 w-full rounded-xl border border-orange-500/50 py-3 text-xs font-black uppercase text-orange-300">Explore Pro</button></section></aside>
    </div>
  </section>;
}
