'use client';
import { FormEvent, useState } from 'react';
const nav=['COMMAND','CHATS','AGENTS','PROJECTS','KNOWLEDGE','MEMORY','TASKS','AUTOMATIONS','CRM & SALES','PHONE (AI)','DISCORD','FILES','TOOLS','MONITORING','LOGS','SETTINGS'];
const agents=['Hermes','Coding','Deploy','HVAC','Sales','Phone','Research','Sound Labs','XR','Design'];
const live=[['Project','WISE² CORE'],['Environment','Production'],['Context Engine','Online'],['Knowledge','Synced'],['Infrastructure','Connected'],['System Alerts','0 critical']];
export default function HermesPage(){
 const [route,setRoute]=useState('AUTO'); const [input,setInput]=useState(''); const [messages,setMessages]=useState<string[]>([]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!input.trim())return;setMessages(v=>[...v,input.trim()]);setInput('');};
 return <main className="min-h-screen bg-[#02070d] p-3 text-[#d9f4ff]">
  <header className="grid gap-3 border border-cyan-500/40 bg-[#04111c] p-4 xl:grid-cols-[1.4fr_1fr_1fr]">
   <div><h1 className="text-3xl font-black tracking-[.08em] text-white">W² WISE² HERMES</h1><p className="text-xs tracking-[.2em] text-cyan-300">YOUR AI OPERATOR · SECOND BRAIN · EXECUTION ENGINE</p></div>
   <div className="flex items-center gap-2">{['AUTO', 'LOCAL', 'CLOUD'].map(x=><button key={x} onClick={()=>setRoute(x)} className={`rounded border px-5 py-2 text-xs font-bold ${route===x?'border-green-400 bg-green-400/15 text-green-300':'border-cyan-800 bg-[#061622] text-cyan-200'}`}>{x}</button>)}</div>
   <div className="grid grid-cols-3 gap-2 text-xs">{['MAC','VPS','GPU'].map(x=><div key={x} className="rounded border border-cyan-800 bg-black/30 p-3 text-center"><span className="text-green-400">●</span> {x} ONLINE</div>)}</div>
  </header>
  <section className="mt-3 grid gap-3 xl:grid-cols-[180px_minmax(0,1.3fr)_minmax(320px,.9fr)_260px]">
   <aside className="rounded border border-cyan-800 bg-[#04101a] p-2">{nav.map((x,i)=><div key={x} className={`mb-1 rounded px-3 py-2 text-xs ${i===0?'bg-cyan-500/15 text-white ring-1 ring-cyan-400':'text-slate-400'}`}>{x}</div>)}</aside>
   <section className="rounded border border-cyan-700 bg-[#04101a] p-4"><div className="flex justify-between border-b border-cyan-900 pb-3"><b className="text-2xl">HERMES</b><span className="text-xs text-green-400">● ONLINE</span></div><div className="h-[500px] space-y-3 overflow-y-auto py-4"><div className="rounded border border-cyan-900 bg-black/30 p-4 text-sm text-slate-300"><b className="text-white">Hermes</b><p className="mt-2">WISE² operating context loaded. Command the business, infrastructure, agents, field systems, or knowledge layer from here.</p></div>{messages.map((m,i)=><div key={i} className="rounded border border-cyan-800 bg-[#071a29] p-4 text-sm"><b>You</b><p className="mt-2 text-slate-300">{m}</p></div>)}</div><div className="rounded border border-cyan-900 bg-black/40 p-3 font-mono text-xs text-cyan-300">$ route {route.toLowerCase()}<br/><span className="text-green-400">✓ WISE² command layer ready</span></div></section>   <section className="relative min-h-[650px] overflow-hidden rounded border border-cyan-700 bg-[radial-gradient(circle_at_50%_42%,rgba(0,174,255,.22),transparent_22%),linear-gradient(180deg,#061526,#02070d)] p-5 text-center">
    <h2 className="text-xl font-black tracking-wider text-white">WISE² COMMAND WORLD</h2><p className="text-[10px] tracking-[.2em] text-cyan-300">REAL-TIME INTELLIGENCE · REAL-WORLD ACTION</p>
    <div className="mx-auto mt-16 flex h-80 w-80 items-center justify-center rounded-full border border-cyan-400/40 bg-cyan-500/5 shadow-[0_0_80px_rgba(0,174,255,.3)]"><div className="flex h-48 w-48 flex-col items-center justify-center rounded-full border-2 border-cyan-300 bg-[#061522] shadow-[0_0_55px_rgba(0,200,255,.45)]"><span className="text-5xl font-black">W²</span><span className="mt-2 text-xs font-bold text-cyan-300">CONTEXT ENGINE</span><span className="mt-3 text-[10px] leading-5 text-slate-400">PEOPLE · PROJECTS<br/>KNOWLEDGE · OPERATIONS<br/>REAL-WORLD IMPACT</span></div></div>
    <div className="absolute left-5 top-44 rounded border border-cyan-700 bg-[#061522]/90 px-3 py-2 text-xs">BUSINESS OPERATIONS</div><div className="absolute right-5 top-52 rounded border border-cyan-700 bg-[#061522]/90 px-3 py-2 text-xs">FIELD OPERATIONS</div><div className="absolute bottom-36 left-8 rounded border border-cyan-700 bg-[#061522]/90 px-3 py-2 text-xs">AI AGENTS</div><div className="absolute bottom-32 right-8 rounded border border-cyan-700 bg-[#061522]/90 px-3 py-2 text-xs">INFRASTRUCTURE</div>
    <p className="absolute bottom-8 left-0 right-0 text-sm font-bold tracking-[.16em] text-cyan-300">ONE CONNECTED OPERATING LAYER<br/><span className="text-[10px] text-slate-500">FROM INTELLIGENCE TO IMPACT</span></p>
   </section>
   <aside className="rounded border border-cyan-800 bg-[#04101a] p-3"><div className="mb-3 flex justify-between"><b>LIVE CONTEXT</b><span className="text-xs text-cyan-400">↻ Sync</span></div>{live.map(([a,b])=><div key={a} className="mb-2 rounded border border-cyan-900 bg-black/30 p-3"><div className="text-[10px] text-slate-500">{a}</div><div className="text-sm text-cyan-100">{b}</div></div>)}<div className="mt-4 border-t border-cyan-900 pt-3 text-xs text-slate-400"><span className="text-green-400">●</span> Operating layer ready<br/><span className="text-green-400">●</span> Field signal strong<br/><span className="text-green-400">●</span> Automation online</div></aside>
  </section>
  <section className="mt-3 rounded border border-cyan-800 bg-[#04101a] p-3"><b className="text-xs">WISE² AGENTS</b><div className="mt-3 flex flex-wrap gap-2">{agents.map((a,i)=><button key={a} className={`rounded border px-4 py-2 text-xs ${i===0?'border-green-400 bg-green-400/10':'border-cyan-900 bg-black/30'}`}>{a} <span className="text-green-400">●</span></button>)}</div>
   <form onSubmit={submit} className="mt-3 flex gap-2"><button type="button" className="rounded border border-cyan-800 px-4">＋</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask Hermes anything..." className="min-w-0 flex-1 rounded border border-cyan-800 bg-[#02070d] px-4 py-3 text-sm outline-none focus:border-cyan-400"/><div className="rounded border border-cyan-800 px-4 py-3 text-xs">Route: <b>{route}</b></div><button className="rounded bg-cyan-500 px-8 font-bold text-black hover:bg-cyan-300">Send</button></form>
  </section>
 </main>;
}