-- WISE DEFENSE Safety Radar + Comms Grid. Additive only; no existing data is changed.
CREATE TYPE "WiseDefenseRole" AS ENUM ('OWNER','ADMIN','OPERATOR','INSTRUCTOR','FAMILY','VIEWER','CUSTOMER');
CREATE TYPE "ThreatLevel" AS ENUM ('LOW','ELEVATED','HIGH','CRITICAL');
CREATE TYPE "VerificationStatus" AS ENUM ('UNVERIFIED','DEVELOPING','CORROBORATED','OFFICIAL','CLEARED');
CREATE TYPE "CommunicationState" AS ENUM ('ONLINE','DEGRADED','OFFLINE','UNKNOWN');
CREATE TYPE "FamilySafetyStatus" AS ENUM ('SAFE','CHECK_IN_REQUESTED','UNKNOWN','NEEDS_HELP');

CREATE TABLE "WiseDefenseMembership" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"user_id" TEXT NOT NULL,"role" "WiseDefenseRole" NOT NULL DEFAULT 'VIEWER',"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "WiseDefenseMembership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Incident" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"provider" TEXT NOT NULL,"provider_incident_id" TEXT,"incident_type" TEXT NOT NULL,"category" TEXT NOT NULL,"headline" TEXT NOT NULL,"description" TEXT,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"approximate_location" TEXT,"city" TEXT,"state" TEXT,"postal_code" TEXT,"source_timestamp" TIMESTAMP(3),"received_timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"status" TEXT NOT NULL DEFAULT 'OPEN',"threat_level" "ThreatLevel" NOT NULL DEFAULT 'LOW',"confidence" INTEGER NOT NULL DEFAULT 0,"verification_status" "VerificationStatus" NOT NULL DEFAULT 'UNVERIFIED',"source_url" TEXT,"audio_url" TEXT,"transcript" TEXT,"ai_summary" TEXT,"source_metadata" JSONB,"is_public" BOOLEAN NOT NULL DEFAULT false,"is_sensitive" BOOLEAN NOT NULL DEFAULT false,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "Incident_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WatchZone" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"name" TEXT NOT NULL,"kind" TEXT NOT NULL,"latitude" DOUBLE PRECISION NOT NULL,"longitude" DOUBLE PRECISION NOT NULL,"radius_miles" DOUBLE PRECISION NOT NULL,"categories" TEXT[] NOT NULL,"minimum_threat" "ThreatLevel" NOT NULL DEFAULT 'ELEVATED',"enabled" BOOLEAN NOT NULL DEFAULT true,"private_location" BOOLEAN NOT NULL DEFAULT true,"notification_destination_ids" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "WatchZone_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MeshNode" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"node_id" TEXT NOT NULL,"long_name" TEXT,"short_name" TEXT,"hardware_model" TEXT,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"altitude" DOUBLE PRECISION,"battery_level" INTEGER,"voltage" DOUBLE PRECISION,"channel_utilization" DOUBLE PRECISION,"air_util_tx" DOUBLE PRECISION,"snr" DOUBLE PRECISION,"rssi" INTEGER,"last_heard" TIMESTAMP(3),"hop_count" INTEGER,"role" TEXT,"online_status" "CommunicationState" NOT NULL DEFAULT 'UNKNOWN',"firmware_version" TEXT,"owner" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "MeshNode_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MeshTelemetry" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"mesh_node_id" TEXT NOT NULL,"batteryLevel" INTEGER,"voltage" DOUBLE PRECISION,"snr" DOUBLE PRECISION,"rssi" INTEGER,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"payload" JSONB,"received_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "MeshTelemetry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RadioDevice" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"name" TEXT NOT NULL,"kind" TEXT NOT NULL,"serial_number" TEXT,"status" "CommunicationState" NOT NULL DEFAULT 'UNKNOWN',"last_check_in" TIMESTAMP(3),"metadata" JSONB,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "RadioDevice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RadioOperator" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"display_name" TEXT NOT NULL,"call_sign" TEXT,"license_class" TEXT,"license_expires_at" TIMESTAMP(3),"status" "CommunicationState" NOT NULL DEFAULT 'UNKNOWN',CONSTRAINT "RadioOperator_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RadioChannel" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"name" TEXT NOT NULL,"service" TEXT NOT NULL,"frequency" TEXT,"tone" TEXT,"offset" TEXT,"band" TEXT,"modulation" TEXT,CONSTRAINT "RadioChannel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Repeater" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"name" TEXT NOT NULL,"service" TEXT NOT NULL,"frequency" TEXT,"tone" TEXT,"offset" TEXT,"status" "CommunicationState" NOT NULL DEFAULT 'UNKNOWN',CONSTRAINT "Repeater_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SDRDevice" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"name" TEXT NOT NULL,"device_type" TEXT NOT NULL,"status" "CommunicationState" NOT NULL DEFAULT 'UNKNOWN',"center_frequency" DOUBLE PRECISION,"span" DOUBLE PRECISION,"gain" DOUBLE PRECISION,"sample_rate" DOUBLE PRECISION,"metadata" JSONB,CONSTRAINT "SDRDevice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SDRSignal" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"sdr_device_id" TEXT,"frequency" DOUBLE PRECISION NOT NULL,"strength_dbm" DOUBLE PRECISION,"classification" TEXT NOT NULL DEFAULT 'UNKNOWN',"detected_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"metadata" JSONB,CONSTRAINT "SDRSignal_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SafetyAlert" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"severity" "ThreatLevel" NOT NULL DEFAULT 'LOW',"status" TEXT NOT NULL DEFAULT 'OPEN',"source_id" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "SafetyAlert_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FamilyMember" ("id" TEXT NOT NULL,"tenant_id" TEXT NOT NULL,"display_name" TEXT NOT NULL,"mesh_node_id" TEXT,"status" "FamilySafetyStatus" NOT NULL DEFAULT 'UNKNOWN',"last_check_in" TIMESTAMP(3),"emergency_contact" TEXT,"private_notes" TEXT,CONSTRAINT "FamilyMember_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "WiseDefenseMembership_tenant_id_user_id_key" ON "WiseDefenseMembership"("tenant_id","user_id");
CREATE UNIQUE INDEX "Incident_tenant_id_provider_provider_incident_id_key" ON "Incident"("tenant_id","provider","provider_incident_id");
CREATE UNIQUE INDEX "MeshNode_tenant_id_node_id_key" ON "MeshNode"("tenant_id","node_id");
CREATE INDEX "Incident_tenant_id_threat_level_received_timestamp_idx" ON "Incident"("tenant_id","threat_level","received_timestamp");
CREATE INDEX "MeshTelemetry_mesh_node_id_received_at_idx" ON "MeshTelemetry"("mesh_node_id","received_at");
CREATE INDEX "SafetyAlert_tenant_id_status_created_at_idx" ON "SafetyAlert"("tenant_id","status","created_at");

ALTER TABLE "WiseDefenseMembership" ADD CONSTRAINT "WiseDefenseMembership_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "Incident" ADD CONSTRAINT "Incident_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "WatchZone" ADD CONSTRAINT "WatchZone_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "MeshNode" ADD CONSTRAINT "MeshNode_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "MeshTelemetry" ADD CONSTRAINT "MeshTelemetry_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "MeshTelemetry" ADD CONSTRAINT "MeshTelemetry_mesh_node_id_fkey" FOREIGN KEY ("mesh_node_id") REFERENCES "MeshNode"("id") ON DELETE CASCADE;
ALTER TABLE "RadioDevice" ADD CONSTRAINT "RadioDevice_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "RadioOperator" ADD CONSTRAINT "RadioOperator_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "RadioChannel" ADD CONSTRAINT "RadioChannel_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "Repeater" ADD CONSTRAINT "Repeater_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "SDRDevice" ADD CONSTRAINT "SDRDevice_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "SafetyAlert" ADD CONSTRAINT "SafetyAlert_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "FamilyMember" ADD CONSTRAINT "FamilyMember_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id") ON DELETE CASCADE;
