[env:byte_mini_esp32s3]
platform = espressif32@7.0.1
board = seeed_xiao_esp32s3
framework = arduino

lib_deps =
    TFT_eSPI @ ^2.5.0

upload_speed = 921600
monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder
    colorize

[env:dev]
extends = env:byte_mini_esp32s3
build_flags =
    -DDEBUG=1
    -DDEBUG_SERIAL=1

[env:release]
extends = env:byte_mini_esp32s3
build_flags =
    -DRELEASE=1
    -O3
