import { randomUUID } from "node:crypto";
import pg from "pg";
export class MemoryUserRepository {
  constructor() { this.users = new Map(); this.states = new Map(); this.videoCredits = new Map(); this.imageEntitlements = new Map(); }
  async init() {}
  async health() { return true; }
  async createUser({ email, passwordHash, displayName }) { if ([...this.users.values()].some((u) => u.email === email)) throw Object.assign(new Error("An account already exists for this email."), { code: "EMAIL_EXISTS" }); const user = { id: randomUUID(), email, passwordHash, displayName, createdAt: new Date().toISOString() }; this.users.set(user.id, user); return user; }
  async findByEmail(email) { return [...this.users.values()].find((u) => u.email === email) || null; }
  async findById(id) { return this.users.get(id) || null; }
  async getState(id) { return this.states.get(id) || { favorites: { version: 2, items: [] }, assets: { version: 1, items: [] }, updatedAt: null }; }
  async saveState(id, state) { const value = { ...state, updatedAt: new Date().toISOString() }; this.states.set(id, value); return value; }
  async getVideoCredits(id) { return Number(this.videoCredits.get(id) || 0); }
  async grantVideoCredits(id, amount) { const next = await this.getVideoCredits(id) + Number(amount); this.videoCredits.set(id, next); return next; }
  async reserveVideoCredits(id, amount) { const balance = await this.getVideoCredits(id); if (balance < amount) return null; const next = balance - amount; this.videoCredits.set(id, next); return next; }
  async refundVideoCredits(id, amount) { return this.grantVideoCredits(id, amount); }
  async getImageEntitlement(id) { const value = this.imageEntitlements.get(id) || { plan:"free",active:false,activeUntil:null,stripeCustomerId:null,stripeSubscriptionId:null,stripeStatus:null }; return { ...value, active:Boolean(value.active) && (!value.activeUntil || new Date(value.activeUntil) > new Date()) }; }
  async setImageEntitlement(id, entitlement) { const current = await this.getImageEntitlement(id); const value = { ...current, ...entitlement, plan:entitlement.plan || current.plan || "free", active:Boolean(entitlement.active), activeUntil:entitlement.activeUntil === undefined ? current.activeUntil : entitlement.activeUntil }; this.imageEntitlements.set(id, value); return value; }
  async findUserIdByStripeCustomer(customerId) { return [...this.imageEntitlements.entries()].find(([,value]) => value.stripeCustomerId === customerId)?.[0] || null; }
}
export class PostgresUserRepository {
  constructor(connectionString) { this.pool = new pg.Pool({ connectionString, max: 10 }); }
  async init() { await this.pool.query(`CREATE TABLE IF NOT EXISTS wt_users (id UUID PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS wt_user_state (user_id UUID PRIMARY KEY REFERENCES wt_users(id) ON DELETE CASCADE, favorites JSONB NOT NULL DEFAULT '{"version":2,"items":[]}', assets JSONB NOT NULL DEFAULT '{"version":1,"items":[]}', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS wt_video_credits (user_id UUID PRIMARY KEY REFERENCES wt_users(id) ON DELETE CASCADE, balance_usd NUMERIC(12,4) NOT NULL DEFAULT 0 CHECK (balance_usd >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS wt_image_entitlements (user_id UUID PRIMARY KEY REFERENCES wt_users(id) ON DELETE CASCADE, plan TEXT NOT NULL DEFAULT 'free', active BOOLEAN NOT NULL DEFAULT FALSE, active_until TIMESTAMPTZ, stripe_customer_id TEXT, stripe_subscription_id TEXT, stripe_status TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); ALTER TABLE wt_image_entitlements ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT; ALTER TABLE wt_image_entitlements ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT; ALTER TABLE wt_image_entitlements ADD COLUMN IF NOT EXISTS stripe_status TEXT; CREATE UNIQUE INDEX IF NOT EXISTS wt_image_entitlements_customer_idx ON wt_image_entitlements(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL; CREATE UNIQUE INDEX IF NOT EXISTS wt_image_entitlements_subscription_idx ON wt_image_entitlements(stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL;`); }
  async health() { await this.pool.query("SELECT 1"); return true; }
  map(r) { return r ? { id: r.id, email: r.email, passwordHash: r.password_hash, displayName: r.display_name, createdAt: r.created_at } : null; }
  async createUser({ email, passwordHash, displayName }) { try { return this.map((await this.pool.query("INSERT INTO wt_users (id,email,password_hash,display_name) VALUES ($1,$2,$3,$4) RETURNING *", [randomUUID(), email, passwordHash, displayName])).rows[0]); } catch (e) { if (e.code === "23505") throw Object.assign(new Error("An account already exists for this email."), { code: "EMAIL_EXISTS" }); throw e; } }
  async findByEmail(email) { return this.map((await this.pool.query("SELECT * FROM wt_users WHERE email=$1", [email])).rows[0]); }
  async findById(id) { return this.map((await this.pool.query("SELECT * FROM wt_users WHERE id=$1", [id])).rows[0]); }
  async getState(id) { const r = (await this.pool.query("SELECT favorites,assets,updated_at FROM wt_user_state WHERE user_id=$1", [id])).rows[0]; return r ? { favorites: r.favorites, assets: r.assets, updatedAt: r.updated_at } : { favorites: { version: 2, items: [] }, assets: { version: 1, items: [] }, updatedAt: null }; }
  async saveState(id, state) { const r = (await this.pool.query("INSERT INTO wt_user_state (user_id,favorites,assets) VALUES ($1,$2,$3) ON CONFLICT (user_id) DO UPDATE SET favorites=EXCLUDED.favorites, assets=EXCLUDED.assets, updated_at=NOW() RETURNING favorites,assets,updated_at", [id, state.favorites, state.assets])).rows[0]; return { favorites: r.favorites, assets: r.assets, updatedAt: r.updated_at }; }
  async getVideoCredits(id) { return Number((await this.pool.query("SELECT balance_usd FROM wt_video_credits WHERE user_id=$1", [id])).rows[0]?.balance_usd || 0); }
  async grantVideoCredits(id, amount) { const r = (await this.pool.query("INSERT INTO wt_video_credits (user_id,balance_usd) VALUES ($1,$2) ON CONFLICT (user_id) DO UPDATE SET balance_usd=wt_video_credits.balance_usd+EXCLUDED.balance_usd, updated_at=NOW() RETURNING balance_usd", [id, amount])).rows[0]; return Number(r.balance_usd); }
  async reserveVideoCredits(id, amount) { await this.pool.query("INSERT INTO wt_video_credits (user_id,balance_usd) VALUES ($1,0) ON CONFLICT DO NOTHING", [id]); const r = (await this.pool.query("UPDATE wt_video_credits SET balance_usd=balance_usd-$2, updated_at=NOW() WHERE user_id=$1 AND balance_usd >= $2 RETURNING balance_usd", [id, amount])).rows[0]; return r ? Number(r.balance_usd) : null; }
  async refundVideoCredits(id, amount) { return this.grantVideoCredits(id, amount); }
  entitlement(r) { return r ? { plan:r.plan,active:Boolean(r.active) && (!r.active_until || new Date(r.active_until)>new Date()),activeUntil:r.active_until,stripeCustomerId:r.stripe_customer_id,stripeSubscriptionId:r.stripe_subscription_id,stripeStatus:r.stripe_status } : { plan:"free",active:false,activeUntil:null,stripeCustomerId:null,stripeSubscriptionId:null,stripeStatus:null }; }
  async getImageEntitlement(id) { return this.entitlement((await this.pool.query("SELECT * FROM wt_image_entitlements WHERE user_id=$1",[id])).rows[0]); }
  async setImageEntitlement(id, entitlement) { const current=await this.getImageEntitlement(id); const value={...current,...entitlement}; const r=(await this.pool.query("INSERT INTO wt_image_entitlements (user_id,plan,active,active_until,stripe_customer_id,stripe_subscription_id,stripe_status) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (user_id) DO UPDATE SET plan=EXCLUDED.plan,active=EXCLUDED.active,active_until=EXCLUDED.active_until,stripe_customer_id=EXCLUDED.stripe_customer_id,stripe_subscription_id=EXCLUDED.stripe_subscription_id,stripe_status=EXCLUDED.stripe_status,updated_at=NOW() RETURNING *",[id,value.plan||"free",Boolean(entitlement.active),entitlement.activeUntil===undefined?current.activeUntil:entitlement.activeUntil,value.stripeCustomerId||null,value.stripeSubscriptionId||null,value.stripeStatus||null])).rows[0]; return this.entitlement(r); }
  async findUserIdByStripeCustomer(customerId) { return (await this.pool.query("SELECT user_id FROM wt_image_entitlements WHERE stripe_customer_id=$1",[customerId])).rows[0]?.user_id || null; }
}
