import ClientMotion from "./client-motion";

const capabilities = ["Strategy", "Brand", "Design", "Content", "Technology", "Experiences", "Growth", "Systems"];
const steps = [["01","Discover","Uncover opportunity at the intersection of vision and reality."],["02","Define","Shape the idea into a strategic foundation."],["03","Design","Transform strategy into creative, technical and operational plans."],["04","Build","Bring every piece to life with the right partners and precision."],["05","Scale","Turn momentum into long-term impact."]];
const work = [["Brand system + campaign","The Pressure Washing Get Down."],["Business intelligence","WISE² OS + REAPER."],["Field operations platform","TRUCK WISER."]];
const workLinks = ["pressure-washing-get-down","wise2-os-reaper","truck-wiser"];
const workImages = ["/assets/project-pressure-washing.png","/assets/project-wise2-os-reaper.png","/assets/project-truck-wiser.png"];
const engagements = [
  {n:"01",name:"Visual Direction Sprint",fit:"For an idea that needs to become visible fast.",time:"First concept in 24 hours",items:["Creative discovery","Visual direction","Hero concept","Recommended build path"],path:"visual-direction"},
  {n:"02",name:"Brand + Launch System",fit:"For a business, product or campaign ready to enter the world.",time:"Built around your scope",items:["Strategy + positioning","Identity system","Website direction","Content + launch assets"],path:"brand-launch"},
  {n:"03",name:"Business + Automation System",fit:"For work that needs to run smarter behind the scenes.",time:"Built around your workflow",items:["Workflow audit","Connected tools","Automation design","Tool-neutral handoff"],path:"business-automation"}
];
const flow = [["Your idea","The starting point."],["WISE²","Two minds. Expanded capability."],["Our system","People, tools and partners aligned."],["Real progress","From concept to commercial reality."],["Lasting impact","A stronger, more connected tomorrow."]];
const questions = [
  ["What can I bring to WISE²?","A rough thought, an existing business, a broken workflow or a nearly finished concept. You do not need a polished brief before we talk."],
  ["Do you only build websites?","No. WISE² connects strategy, branding, content, technology, automation and operations. A website may be one part of the larger system."],
  ["Do I have to use specific software?","No. We design tool-neutral handoffs so your project can move between the right people and platforms without being trapped in one tool."],
  ["What happens after I submit?","We review the idea, identify what is already clear, ask only the questions needed to define scope, then recommend the strongest build path, timeline and cost."],
  ["How does the 24-hour visual work?","Once the direction and required inputs are confirmed, the Visual Direction Sprint produces the first presentation-ready concept within 24 hours."],
  ["Can the service paths be combined?","Yes. They are starting points, not boxes. Creative, technical and operational work can be connected into one custom A–Z engagement."]
];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){return <main>
  <ClientMotion/>
  <header className="nav shell"><a className="logo" href="#top">WISE<sup>2</sup></a><nav><a href="#work">Work</a><a href="#approach">Approach</a><a href="#services">Services</a><a href="#ecosystem">Ecosystem</a><a href="#about">About</a></nav><details className="mobile-menu"><summary aria-label="Open navigation"><i/><i/><i/></summary><div><a href="#work">Work</a><a href="#approach">Approach</a><a href="#services">Services</a><a href="#ecosystem">Ecosystem</a><a href="#about">About</a><a href="/start">Start a project</a></div></details><a className="button small desktop-cta" href="/start">Build with WISE² <Arrow/></a></header>
  <section className="hero shell" id="top"><div className="hero-copy reveal"><p className="eyebrow">Creative technology for a more connected tomorrow</p><h1 className="hero-title"><span>Two minds.</span><span>One vision.</span></h1><p className="lede hero-lede"><span>Ideas become systems.</span><span>Systems create momentum.</span><span>Momentum becomes impact.</span></p><div className="actions"><a className="button" href="/start">Build with WISE² <Arrow/></a><a className="text-link" href="#approach">Explore the system <Arrow/></a></div></div><div className="hero-art reveal"><div className="halo"/><img src="/assets/wise2-future-foundry-hero.png" alt="Carved WISE² processor sculpture connecting strategy, creativity, technology, content and growth"/></div><p className="side-note">Different disciplines.<br/>A higher outcome.</p></section>
  <div className="ticker"><div>{capabilities.map(c=><span key={c}>{c}</span>)}</div></div>
  <section className="about shell" id="about"><div className="about-mark" aria-hidden="true"><span>W</span><sup>2</sup></div><div className="about-copy"><p className="eyebrow">Why WISE²</p><h2>One idea.<br/>Two ways of seeing it.</h2><p className="about-lede">WISE² is built on a simple advantage: one mind sees what an idea could become while the other sees how to make it real.</p><div className="mind-grid"><article><b>01</b><h3>Creative intelligence</h3><p>We uncover the story, identity and experience that make the idea worth remembering.</p></article><article><b>02</b><h3>Systems intelligence</h3><p>We connect the tools, technology and operations that make the idea work in the real world.</p></article></div><p className="about-close">Not two separate services. One connected vision—designed, built and prepared to grow.</p></div></section>
  <section className="process porcelain" id="approach"><div className="shell"><div className="section-head"><p className="eyebrow dark">The WISE² process</p><h2>From one idea to a complete system.</h2></div><img className="process-art" src="/assets/wise2-process-transformation-strip.png" alt="Five sculpted stages progressing from raw stone to a finished future system"/><div className="steps">{steps.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="work shell" id="work"><div className="section-head split"><div><p className="eyebrow">Selected WISE² systems</p><h2>Ideas in the<br/>real world.</h2></div><a className="text-link" href="/start">Bring us your idea <Arrow/></a></div><div className="work-grid">{work.map(([k,t],i)=><a href={`/work/${workLinks[i]}`} className={`project p${i+1}`} key={k}><div className="project-visual"><span>0{i+1}</span><img src={workImages[i]} alt=""/></div><p>{k}</p><h3>{t}</h3><Arrow/></a>)}</div><div className="active-systems"><span>Also in the foundry</span><b>Sublily</b><b>SIDE EYE</b><b>WISE Voice</b><b>AIRSHIFT</b><b>WISE² FairWork</b></div></section>
  <section className="services porcelain" id="services"><div className="shell"><div className="section-head service-head"><div><p className="eyebrow dark">Ways to build with WISE²</p><h2>Start where<br/>you are.</h2></div><p>Every engagement begins with the real problem—not a preset stack. Choose the closest path and we will shape the right system around it.</p></div><div className="service-grid">{engagements.map(x=><article key={x.n}><div className="service-top"><b>{x.n}</b><span>{x.time}</span></div><h3>{x.name}</h3><p>{x.fit}</p><ul>{x.items.map(item=><li key={item}>{item}</li>)}</ul><a className="service-link" href={`/start?path=${x.path}`}>Choose this path <Arrow/></a></article>)}</div><div className="service-note"><b>No box fits?</b><span>Bring the rough idea. We can combine creative, technical and operational work into one custom A–Z system.</span><a href="/start">Start custom ↗</a></div></div></section>
  <section className="flow shell"><div className="section-head"><p className="eyebrow">How we work</p><h2>One partner.<br/>Every moving piece.</h2></div><div className="flow-grid">{flow.map(([t,d],i)=><article key={t}><span className="flow-icon">{i===1?"◉":"○"}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="manifesto" aria-label="The WISE² way"><div><span>Think it.</span><span>Shape it.</span><span>Build it.</span></div></section>
  <section className="ecosystem" id="ecosystem"><div className="shell eco-grid"><div className="eco-copy"><p className="eyebrow">A connected ecosystem</p><h2>More than a studio.<br/>A living ecosystem.</h2><p className="body-copy">Strategic partners. Specialist talent. Global reach. All working together through WISE².</p><a className="button" href="#contact">Connect your idea <Arrow/></a></div><div className="eco-cinematic"><img src="/assets/wise2-ecosystem-cinematic.png" alt="A cinematic mineral-glass intelligence ecosystem connected by brass energy filaments"/><span className="eco-flare" aria-hidden="true"/><p>Every signal becomes momentum.</p></div></div></section>
  <section className="metrics porcelain"><div className="shell metric-grid"><p className="eyebrow dark">The WISE² promise</p>{[["24 HR","Visual mock-up"],["2","Minds"],["1","Connected vision"],["A–Z","Idea to launch"],["3","Tool-neutral handoffs"]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
  <section className="trust shell"><div className="section-head trust-head"><div><p className="eyebrow">Built for a clean handoff</p><h2>Clear from idea<br/>to ownership.</h2></div><p>Before work begins, the scope, outputs and next decisions are made visible. During the build, creative and technical pieces stay connected. At handoff, your system is organized to keep moving.</p></div><div className="trust-grid"><article><b>01</b><h3>Clear scope</h3><p>Know what is being built, what is included and which decisions come next.</p></article><article><b>02</b><h3>Connected build</h3><p>Strategy, visuals, content and technology are developed as one system.</p></article><article><b>03</b><h3>Portable handoff</h3><p>Files and instructions are prepared so the work can continue across the right tools and partners.</p></article></div></section>
  <section className="faq porcelain"><div className="shell faq-grid"><div><p className="eyebrow dark">Before we build</p><h2>Good questions.<br/>Clear answers.</h2><a className="button" href="/start">Bring us yours <Arrow/></a></div><div className="faq-list">{questions.map(([q,a],i)=><details key={q} open={i===0}><summary><span>0{i+1}</span>{q}<b aria-hidden="true">+</b></summary><p>{a}</p></details>)}</div></div></section>
  <section className="final shell" id="contact"><div><p className="eyebrow">It starts here</p><h2>Your idea is ready<br/>for a system.</h2></div><p>Let’s turn it into something bigger—together.</p><a className="button" href="/start">Build with WISE² <Arrow/></a></section>
  <footer className="shell"><a className="logo" href="#top">WISE<sup>2</sup></a><p>Two minds. One vision.</p><p>Creative systems for a brighter tomorrow.</p><p>© {new Date().getFullYear()} WISE²</p></footer>
</main>}
