import ClientMotion from "./client-motion";

const capabilities = ["Strategy", "Brand", "Design", "Content", "Technology", "Experiences", "Growth", "Systems"];
const steps = [["01","Discover","Uncover opportunity at the intersection of vision and reality."],["02","Define","Shape the idea into a strategic foundation."],["03","Design","Transform strategy into creative, technical and operational plans."],["04","Build","Bring every piece to life with the right partners and precision."],["05","Scale","Turn momentum into long-term impact."]];
const work = [["Brand system + campaign","The Pressure Washing Get Down."],["Business intelligence","WISE² OS + REAPER."],["Field operations platform","TRUCK WISER."]];
const workLinks = ["pressure-washing-get-down","wise2-os-reaper","truck-wiser"];
const workImages = ["/assets/project-pressure-washing.png","/assets/project-wise2-os-reaper.png","/assets/project-truck-wiser.png"];
const flow = [["Your idea","The starting point."],["WISE²","Two minds. Expanded capability."],["Our system","People, tools and partners aligned."],["Real progress","From concept to commercial reality."],["Lasting impact","A stronger, more connected tomorrow."]];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){return <main>
  <ClientMotion/>
  <header className="nav shell"><a className="logo" href="#top">WISE<sup>2</sup></a><nav><a href="#work">Work</a><a href="#approach">Approach</a><a href="#ecosystem">Ecosystem</a><a href="#contact">About</a></nav><details className="mobile-menu"><summary aria-label="Open navigation"><i/><i/><i/></summary><div><a href="#work">Work</a><a href="#approach">Approach</a><a href="#ecosystem">Ecosystem</a><a href="/start">Start a project</a></div></details><a className="button small desktop-cta" href="/start">Build with WISE² <Arrow/></a></header>
  <section className="hero shell" id="top"><div className="hero-copy reveal"><p className="eyebrow">Creative technology for a more connected tomorrow</p><h1><span>Two minds.</span><span>One vision.</span></h1><p className="lede">Ideas become systems.</p><div className="actions"><a className="button" href="/start">Build with WISE² <Arrow/></a><a className="text-link" href="#approach">Explore the system <Arrow/></a></div></div><div className="hero-art reveal"><div className="halo"/><img src="/assets/wise2-future-foundry-hero.png" alt="Carved WISE² processor sculpture connecting strategy, creativity, technology, content and growth"/></div><p className="side-note">Different disciplines.<br/>A higher outcome.</p></section>
  <div className="ticker"><div>{capabilities.map(c=><span key={c}>{c}</span>)}</div></div>
  <section className="process porcelain" id="approach"><div className="shell"><div className="section-head"><p className="eyebrow dark">The WISE² process</p><h2>From one idea to a complete system.</h2></div><img className="process-art" src="/assets/wise2-process-transformation-strip.png" alt="Five sculpted stages progressing from raw stone to a finished future system"/><div className="steps">{steps.map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="work shell" id="work"><div className="section-head split"><div><p className="eyebrow">Selected WISE² systems</p><h2>Ideas in the<br/>real world.</h2></div><a className="text-link" href="/start">Bring us your idea <Arrow/></a></div><div className="work-grid">{work.map(([k,t],i)=><a href={`/work/${workLinks[i]}`} className={`project p${i+1}`} key={k}><div className="project-visual"><span>0{i+1}</span><img src={workImages[i]} alt=""/></div><p>{k}</p><h3>{t}</h3><Arrow/></a>)}</div><div className="active-systems"><span>Also in the foundry</span><b>Sublily</b><b>SIDE EYE</b><b>WISE Voice</b><b>AIRSHIFT</b><b>WISE² FairWork</b></div></section>
  <section className="flow shell"><div className="section-head"><p className="eyebrow">How we work</p><h2>One partner.<br/>Every moving piece.</h2></div><div className="flow-grid">{flow.map(([t,d],i)=><article key={t}><span className="flow-icon">{i===1?"◉":"○"}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="ecosystem" id="ecosystem"><div className="shell eco-grid"><div><p className="eyebrow">A connected ecosystem</p><h2>More than a studio.<br/>A living ecosystem.</h2><p className="body-copy">Strategic partners. Specialist talent. Global reach. All working together through WISE².</p><a className="button" href="#contact">Explore the ecosystem <Arrow/></a></div><div className="circuit"><span className="core">W<sup>2</sup></span>{["Creative studios","Tech partners","Investors","Global markets","Cultural connectors","Industry experts"].map((x,i)=><span className={`node n${i+1}`} key={x}>{x}</span>)}</div></div></section>
  <section className="metrics porcelain"><div className="shell metric-grid"><p className="eyebrow dark">The WISE² promise</p>{[["24 HR","Visual mock-up"],["2","Minds"],["1","Connected vision"],["A–Z","Idea to launch"],["3","Tool-neutral handoffs"]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
  <section className="final shell" id="contact"><div><p className="eyebrow">It starts here</p><h2>Your idea is ready<br/>for a system.</h2></div><p>Let’s turn it into something bigger—together.</p><a className="button" href="/start">Build with WISE² <Arrow/></a></section>
  <footer className="shell"><a className="logo" href="#top">WISE<sup>2</sup></a><p>Two minds. One vision.</p><p>Creative systems for a brighter tomorrow.</p><p>© {new Date().getFullYear()} WISE²</p></footer>
</main>}
