import {blast,detonate,directions,key,path,same,tile} from './grid.mjs';
export const defaults={fuse:2.2,flameDuration:.45,moveInterval:.12,enemyInterval:.38,capacity:2,radius:2};
const map=['#############','#...+.......#','#.#.#.#.#.#.#','#...+...+...#','#.#.#.#.#.#.#','#...+.......#','#.#.#.#.#.#.#','#.......+...#','#############'];
export class Round {
  constructor(config={}) {this.config={...defaults,...config};this.restart();}
  restart(){this.grid=map.map(r=>[...r]);this.player=[1,1];this.enemy=[11,7];this.bombs=[];this.flames=[];this.energy=[[3,1],[1,7],[11,1]];this.upgrade=[3,3];this.radius=this.config.radius;this.score=0;this.status='playing';this.time=0;this.nextId=1;this.enemyAt=0;this.moveAt=0;}
  move(dx,dy){if(this.status!=='playing'||this.time<this.moveAt||Math.abs(dx)+Math.abs(dy)!==1)return;const p=[this.player[0]+dx,this.player[1]+dy];if(tile(this.grid,p)!=='.'||this.bombs.some(b=>same(b.position,p)))return;this.player=p;this.moveAt=this.time+this.config.moveInterval;this.energy=this.energy.filter(e=>{if(same(e,p)){this.score+=10;return false;}return true;});if(this.upgrade&&same(p,this.upgrade)){this.radius++;this.upgrade=null;}this.check();}
  place(){if(this.status!=='playing'||this.bombs.length>=this.config.capacity||this.bombs.some(b=>same(b.position,this.player)))return;this.bombs.push({id:this.nextId++,position:[...this.player],radius:this.radius,at:this.time+this.config.fuse});}
  danger(){const d=new Set(this.flames.map(f=>key(f.position)));for(const b of this.bombs)for(const p of blast(this.grid,b.position,b.radius))d.add(key(p));return d;}
  tick(dt){if(this.status!=='playing')return;this.time+=Math.min(Math.max(dt,0),.1);this.flames=this.flames.filter(f=>f.until>this.time);for(const b of [...this.bombs])if(b.at<=this.time&&this.bombs.some(x=>x.id===b.id)){const result=detonate(this.grid,this.bombs,b);this.bombs=this.bombs.filter(x=>!result.fired.has(x.id));this.flames.push(...result.cells.map(position=>({position,until:this.time+this.config.flameDuration})));}if(this.enemy&&this.flames.some(f=>same(f.position,this.enemy))){this.enemy=null;this.score+=50;}if(this.enemy&&this.time>=this.enemyAt){this.enemyAt=this.time+this.config.enemyInterval;const danger=this.danger(),blocked=new Set([...danger,...this.bombs.map(b=>key(b.position))]);let route=[];if(danger.has(key(this.enemy))){for(let y=1;y<this.grid.length-1;y++)for(let x=1;x<this.grid[0].length-1;x++){const p=[x,y];if(tile(this.grid,p)!=='.'||blocked.has(key(p)))continue;const candidate=path(this.grid,this.enemy,p,new Set(this.bombs.map(b=>key(b.position))));if(candidate.length>1&&(!route.length||candidate.length<route.length))route=candidate;}}else route=path(this.grid,this.enemy,this.player,blocked);if(route.length>1)this.enemy=route[1];}this.check();}
  check(){if(this.flames.some(f=>same(f.position,this.player))||(this.enemy&&same(this.player,this.enemy)))this.status='lost';else if(!this.enemy&&!this.energy.length)this.status='won';}
}
