"use client";
import {useMemo,useState} from "react";
type Item={id:string;title:string;project:string;owner:string;priority:"Critical"|"High"|"Medium"|"Low";status:"Backlog"|"In Progress"|"Review"|"Done";link:string};
const initial:Item[]=[
{id:"WISE-153",title:"Unify WISE² Connect, Hermes and Git Assassin",project:"WISE² Connect",owner:"Core",priority:"High",status:"Review",link:"https://github.com/dwise03-bit/wise2-core/pull/153"},
{id:"WISE-141",title:"Repair failing GitHub Actions",project:"Infrastructure",owner:"DevOps",priority:"Critical",status:"Review",link:"https://github.com/dwise03-bit/wise2-core/pull/141"},
{id:"WISE-139",title:"Repair deployment SSH authentication",project:"Infrastructure",owner:"DevOps",priority:"Critical",status:"Review",link:"https://github.com/dwise03-bit/wise2-core/pull/139"},
{id:"WISE-82",title:"Hermes actions management integration",project:"Hermes",owner:"AI",priority:"High",status:"Review",link:"https://github.com/dwise03-bit/wise2-core/pull/82"},
{id:"WISE-77",title:"Secure Discord alert integration",project:"Living Hive",owner:"Core",priority:"High",status:"Review",link:"https://github.com/dwise03-bit/wise2-core/pull/77"}
];
const stages:Item["status"][]=["Backlog","In Progress","Review","Done"];
export default function ProjectBoard(){
 const [items,setItems]=useState(initial),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[title,setTitle]=useState(""),[project,setProject]=useState("WISE² Connect");
 const [files,setFiles]=useState<{name:string;size:number;type:string}[]>([]);
 const shown=useMemo(()=>items.filter(x=>(filter==="All"||x.project===filter)&&[x.title,x.project,x.id].join(" ").toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 const projects=["All",...Array.from(new Set(items.map(x=>x.project)))];
 const add=()=>{if(!title.trim())return;setItems(old=>[{id:"LOCAL-"+Date.now(),title:title.trim(),project,owner:"Unassigned",priority:"Medium",status:"Backlog",link:""},...old]);setTitle("")};
 return <main style={{minHeight:"100vh",background:"radial-gradient(ellipse at top,#102b52,#060c18 60%)",color:"#eaf4ff",fontFamily:"system-ui",padding:"clamp(16px,4vw,44px)"}}>
 <style>{`.pb-card{border:1px solid #285273;border-radius:13px;background:#0c2035;padding:15px}.pb-button{background:#102b43;color:#d9f5ff;border:1px solid #31668b;border-radius:9px;padding:9px 12px;cursor:pointer}.pb-button:hover{border-color:#70ffad} input,select{background:#091b2d;color:#eaf4ff;border:1px solid #2e5775;border-radius:9px;padding:10px}`}</style>
 <header style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:14,alignItems:"center",borderBottom:"1px solid #214469",paddingBottom:22}}>
 <div><div style={{fontSize:12,letterSpacing:3,color:"#68ffae"}}>WISE² CONNECT / LIVING HIVE</div><h1 style={{fontSize:"clamp(30px,5vw,52px)",margin:"8px 0"}}>PROJECT BOARD</h1><p style={{color:"#9db9d0"}}>Portfolio execution · Shared files · Review queue</p></div><a href="/connect" style={{color:"#70d9ff"}}>← Connect Command</a></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,margin:"22px 0"}}>{[["Projects",String(projects.length-1)],["Tracked cards",String(items.length)],["Needs review",String(items.filter(x=>x.status==="Review").length)],["Central file share","Not connected"]].map(([a,b])=><div className="pb-card" key={a}><div style={{color:"#75ffb1",fontSize:23}}>{b}</div><small style={{color:"#9cb5ca"}}>{a}</small></div>)}</section>
 <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:18}}><input aria-label="Search cards" placeholder="Search projects or tasks" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter project" value={filter} onChange={e=>setFilter(e.target.value)}>{projects.map(x=><option key={x}>{x}</option>)}</select></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12}}>{stages.map(stage=><section key={stage} className="pb-card"><h2 style={{fontSize:18,color:"#9bd6ff"}}>{stage} <span style={{color:"#73ffaf"}}>{shown.filter(x=>x.status===stage).length}</span></h2>{shown.filter(x=>x.status===stage).map(x=><article key={x.id} style={{border:"1px solid #2a536b",borderRadius:10,padding:12,marginBottom:10,background:"#0b192b"}}><small style={{color:"#70ffaf"}}>{x.id} · {x.priority}</small><h3 style={{fontSize:15,margin:"8px 0"}}>{x.title}</h3><p style={{fontSize:12,color:"#9bb4c8"}}>{x.project} · {x.owner}</p>{x.link&&<a href={x.link} target="_blank" rel="noopener noreferrer" style={{color:"#7cdaff",fontSize:13}}>Open source PR ↗</a>}<div style={{marginTop:12}}><select aria-label={"Status for "+x.title} value={x.status} onChange={e=>setItems(old=>old.map(y=>y.id===x.id?{...y,status:e.target.value as Item["status"]}:y))}>{stages.map(s=><option key={s}>{s}</option>)}</select></div></article>)}</section>)}</div>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:14,marginTop:24}}>
 <div className="pb-card"><h2>New task</h2><p style={{color:"#9eb9cd",fontSize:13}}>Local board prototype. Changes are not saved to the server.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input aria-label="Task title" placeholder="Task title" value={title} onChange={e=>setTitle(e.target.value)}/><input aria-label="Project name" value={project} onChange={e=>setProject(e.target.value)}/><button className="pb-button" onClick={add}>Add card</button></div></div>
 <div className="pb-card"><h2>CENTRAL FILE SHARE</h2><p style={{color:"#9eb9cd",fontSize:13}}>Choose files to stage locally. No file is uploaded or shared until authenticated storage and access controls are connected.</p><input type="file" multiple aria-label="Stage files" onChange={e=>setFiles(Array.from(e.target.files||[]).map(f=>({name:f.name,size:f.size,type:f.type})))}/>{files.map((f,i)=><p key={i} style={{fontSize:13}}>{f.name} · {(f.size/1024).toFixed(1)} KB <span style={{color:"#ffcd80"}}>Not uploaded</span></p>)}<p style={{fontSize:12,color:"#ffcd80"}}>Required backend: project permissions, virus scanning, encrypted storage, signed download URLs, version history, and audit events.</p></div>
 </section><footer style={{marginTop:24,color:"#93adc4",fontSize:12}}>Demo task state only. PR links reflect known GitHub records; no project files are publicly exposed.</footer></main>
}