import type { AgentName, ControlConfig, TaskHandoff, TaskRecord } from '../types.js';
import { handoffFor, statusFromHandoff, updateTask } from './tasks.js';
export async function dispatchTask(config: ControlConfig, task: TaskRecord, agent: AgentName = task.preferredAgent, fetchImpl: typeof fetch = globalThis.fetch): Promise<{ task: TaskRecord; handoff: TaskHandoff }> {
  if (task.approvalRequired) { const handoff = handoffFor(task, agent, { status: 'BLOCKED', summary: 'Human approval is required before dispatch.', next: 'Obtain approval, then dispatch the task.' }); return { task: await updateTask(config.taskFile, task, { status: 'blocked', currentAgent: agent, handoff }), handoff }; }
  let handoff: TaskHandoff;
  if (agent !== 'local') handoff = handoffFor(task, agent, { status: 'PARTIAL', summary: `No ${agent} execution adapter is configured.`, blockers: [`${agent} adapter not configured`], next: 'Configure the approved worker adapter, then retry.' });
  else { try { const response = await fetchImpl(config.ollamaChatUrl, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: config.ollamaModel, stream: false, messages: [{ role: 'user', content: `${task.goal}\n\nRepository: ${task.repoPath}\nContext: ${task.context ?? ''}` }] }), signal: AbortSignal.timeout(config.workerTimeoutMs) }); if (!response.ok) throw new Error(`Ollama returned HTTP ${response.status}`); const result = await response.json() as { message?: { content?: string } }; handoff = handoffFor(task, agent, { status: 'SUCCESS', summary: result.message?.content ?? 'Local worker completed without a textual summary.', next: 'Run the declared verification command and review the diff.' }); } catch (error) { handoff = handoffFor(task, agent, { status: 'BLOCKED', summary: 'Local worker could not be reached.', blockers: [(error as Error).message], next: 'Start Ollama or select a configured worker.' }); } }
  const next = await updateTask(config.taskFile, task, { status: statusFromHandoff(handoff), currentAgent: agent, handoff }); return { task: next, handoff };
}
