import { appendFile, mkdir, readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { AgentName, TaskContract, TaskHandoff, TaskRecord, TaskStatus } from '../types.js';
async function append(file: string, record: TaskRecord) { await mkdir(dirname(file), { recursive: true }); await appendFile(file, `${JSON.stringify(record)}\n`, 'utf8'); }
export async function readTasks(file: string): Promise<TaskRecord[]> { try { const text = await readFile(file, 'utf8'); const latest = new Map<string, TaskRecord>(); for (const line of text.trim().split('\n').filter(Boolean)) { const task = JSON.parse(line) as TaskRecord; latest.set(task.taskId, task); } return [...latest.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error; } }
export async function createTask(file: string, input: Omit<TaskContract, 'taskId'> & { taskId?: string }): Promise<TaskRecord> { const now = new Date().toISOString(); const task: TaskRecord = { ...input, taskId: input.taskId ?? `W2-${new Date().toISOString().slice(0, 10)}-${randomUUID().slice(0, 8)}`, status: 'queued', createdAt: now, updatedAt: now }; await append(file, task); return task; }
export async function updateTask(file: string, task: TaskRecord, patch: Partial<Pick<TaskRecord, 'status' | 'currentAgent' | 'branch' | 'changed' | 'tests' | 'blockers' | 'handoff'>>): Promise<TaskRecord> { const next = { ...task, ...patch, updatedAt: new Date().toISOString() }; await append(file, next); return next; }
export function handoffFor(task: TaskRecord, agent: AgentName, patch: Partial<TaskHandoff> = {}): TaskHandoff { const status: TaskHandoff['status'] = task.status === 'succeeded' ? 'SUCCESS' : task.status === 'blocked' ? 'BLOCKED' : task.status === 'failed' ? 'FAILED' : 'PARTIAL'; return { status, taskId: task.taskId, summary: 'Task accepted by the control router.', changed: task.changed ?? [], tested: task.tests ?? [], blockers: task.blockers ?? [], risks: [], next: 'Dispatch to the selected worker.', needsHumanApproval: task.approvalRequired, agent, timestamp: new Date().toISOString(), ...patch }; }
export function statusFromHandoff(handoff: TaskHandoff): TaskStatus { return ({ SUCCESS: 'succeeded', PARTIAL: 'partial', BLOCKED: 'blocked', FAILED: 'failed' } as const)[handoff.status]; }
