'use client';

import { useEffect, useRef, useState } from 'react';
import { Activity, Camera, Check, CircleStop, Cloud, FileText, Mic, Pause, Play, Radio, RotateCcw, Save, ShieldCheck, Square, Users, Video, Wifi, WifiOff, Zap } from 'lucide-react';
import './connect.css';

type CaptureType = 'audio' | 'video';
type Capture = { id: string; type: CaptureType; createdAt: string; duration: number; status: 'LOCAL' | 'SYNC'; blob?: Blob };
type Audit = { client: string; contact: string; objective: string };
const DB_NAME='wise2-connect-captures', STORE='captures';
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function readCaptures():Promise<Capture[]>{if(!('indexedDB'in window))return[];const db=await openDb();return new Promise(resolve=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve((r.result as Capture[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));});}
async function saveCapture(c:Capture){const db=await openDb();return new Promise<void>((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(c);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
const fmt=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

export default function ConnectPage(){
 const [mode,setMode]=useState<CaptureType>('audio'),[state,setState]=useState<'idle'|'recording'|'paused'|'preview'>('idle'),[elapsed,setElapsed]=useState(0),[captures,setCaptures]=useState<Capture[]>([]),[previewUrl,setPreviewUrl]=useState<string>();
 const [message,setMessage]=useState('Ready. Nothing is captured without permission.'),[notice,setNotice]=useState(''),[online,setOnline]=useState(true),[audit,setAudit]=useState<Audit>({client:'',contact:'',objective:''}),[auditOpen,setAuditOpen]=useState(false),[activeAudit,setActiveAudit]=useState<Audit|null>(null);
 const recorder=useRef<MediaRecorder>(),stream=useRef<MediaStream>(),chunks=useRef<Blob[]>([]),startedAt=useRef(0),tick=useRef<ReturnType<typeof setInterval>>();
 useEffect(()=>{setOnline(navigator.onLine);const up=()=>setOnline(true),down=()=>setOnline(false);addEventListener('online',up);addEventListener('offline',down);readCaptures().then(setCaptures).catch(()=>setMessage('Local storage unavailable.'));return()=>{removeEventListener('online',up);removeEventListener('offline',down);stream.current?.getTracks().forEach(t=>t.stop());if(tick.current)clearInterval(tick.current);};},[]);
 const start=async()=>{try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('This browser does not support local recording.');stream.current=await navigator.mediaDevices.getUserMedia(mode==='video'?{video:true,audio:true}:{audio:true});chunks.current=[];recorder.current=new MediaRecorder(stream.current);recorder.current.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);recorder.current.onstop=()=>{const blob=new Blob(chunks.current,{type:recorder.current?.mimeType||(mode==='video'?'video/webm':'audio/webm')});setPreviewUrl(URL.createObjectURL(blob));setState('preview');if(tick.current)clearInterval(tick.current);stream.current?.getTracks().forEach(t=>t.stop());};recorder.current.start();startedAt.current=Date.now();setElapsed(0);setState('recording');setMessage(`Recording ${mode} locally. Keep participants informed.`);tick.current=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),250);}catch(e){setMessage(e instanceof DOMException&&e.name==='NotAllowedError'?'Permission denied. Allow microphone/camera access.':e instanceof Error?e.message:'Recording could not start.');setState('idle');}};
 const pause=()=>{if(!recorder.current)return;if(state==='recording'){recorder.current.pause();setElapsed(Math.floor((Date.now()-startedAt.current)/1000));setState('paused');setMessage('Recording paused.');}else{recorder.current.resume();startedAt.current=Date.now()-elapsed*1000;setState('recording');setMessage('Recording resumed.');}};
 const discard=()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl(undefined);chunks.current=[];setElapsed(0);setState('idle');setMessage('Capture discarded.');};
 const save=async()=>{const c:Capture={id:crypto.randomUUID(),type:mode,createdAt:new Date().toISOString(),duration:elapsed,status:'LOCAL',blob:new Blob(chunks.current)};await saveCapture(c);setCaptures(await readCaptures());setMessage('Saved locally. Ready for Audit Record or Reaper.');setState('idle');};
 const beginAudit=()=>{if(!audit.client.trim()){setNotice('Add a business/client name to start the audit.');return;}setActiveAudit(audit);setAuditOpen(false);setNotice(`Audit started for ${audit.client}. Capture evidence below.`);};
 const createAudit=(c:Capture)=>setNotice(`Audit Record linked · ${new Date(c.createdAt).toLocaleString()} · ${c.type} · ${fmt(c.duration)} · ${c.status}`);
 const notifyDiscord=async(c:Capture)=>{setNotice('Sending capture metadata to Discord…');try{const response=await fetch('/api/connect/captures/discord',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:c.type,duration:c.duration,createdAt:c.createdAt,status:c.status,client:activeAudit?.client})});const result=await response.json();setNotice(result.sent?'Discord notified.':result.configured===false?'Discord webhook is not configured on this deployment.':'Discord notification failed.');}catch{setNotice('Discord notification failed.');}};
 const sendReaper=(c:Capture)=>{setNotice(activeAudit?`Reaper handoff staged for ${activeAudit.client}. Capture remains local until an authenticated prospect is selected.`:'Start an audit first so Reaper has client context.');};
 return <main className="connect-shell"><header className="connect-header"><div><div className="brandline"><span className="brandmark">W²</span><span className="eyebrow">WISE² CONNECT / FIELD COMMAND</span></div><h1>Capture the room.<br/><span>Turn it into action.</span></h1><p>One field workspace for conversations, evidence, business audits and team handoff.</p></div><div className={`state-pill ${online?'online':''}`}>{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?'ONLINE':'LOCAL'} <span>•</span> CAPTURE READY</div></header>
 <nav className="command-strip"><button className="active"><Activity size={15}/>Connect</button><button onClick={()=>setAuditOpen(true)}><FileText size={15}/>Business Audit</button><button><Users size={15}/>Team</button><button><Radio size={15}/>Channels</button><button><Zap size={15}/>Reaper</button><span/><b>{activeAudit?`AUDIT · ${activeAudit.client}`:'NO ACTIVE AUDIT'}</b></nav>
 <section className="hero-actions"><button className="audit-hero" onClick={()=>setAuditOpen(true)}><span><FileText size={23}/></span><div><small>FIELD WORKFLOW</small><strong>{activeAudit?'Audit in progress':'Start Business Audit'}</strong><p>{activeAudit?activeAudit.client:'Create the client record, then capture evidence.'}</p></div></button><div className="pipeline"><small>WISE² PIPELINE</small><div><b>CAPTURE</b><i>→</i><b>AI</b><i>→</i><b>REAPER</b><i>→</i><b>CRM</b><i>→</i><b>DISCORD</b></div><p>Local-first capture. Cloud processing only when you choose to sync.</p></div></section>
 {auditOpen&&<section className="audit-builder"><div><small>NEW BUSINESS AUDIT</small><h2>Who are we auditing?</h2></div><input aria-label="Business or client" placeholder="Business / client *" value={audit.client} onChange={e=>setAudit({...audit,client:e.target.value})}/><input aria-label="Contact" placeholder="Contact name" value={audit.contact} onChange={e=>setAudit({...audit,contact:e.target.value})}/><input aria-label="Audit objective" placeholder="Audit objective / opportunity" value={audit.objective} onChange={e=>setAudit({...audit,objective:e.target.value})}/><button onClick={beginAudit}>Begin Audit</button><button className="close" onClick={()=>setAuditOpen(false)}>Cancel</button></section>}
 <section className="connect-grid"><div className="record-card"><div className="card-top"><div><span className="eyebrow">QUICK CAPTURE</span><h2>Record field intelligence</h2></div><ShieldCheck className="blue-icon"/></div><p className="consent">Recording starts only after browser permission. Keep participants informed before you begin.</p><div className="mode-tabs"><button className={mode==='audio'?'active':''} onClick={()=>setMode('audio')} disabled={state!=='idle'}><Mic size={18}/>Audio</button><button className={mode==='video'?'active':''} onClick={()=>setMode('video')} disabled={state!=='idle'}><Video size={18}/>Video + audio</button></div><div className={`record-orb ${state==='recording'?'is-recording':''}`}><div className="orb-center">{state==='preview'?<Check size={34}/>:mode==='video'?<Camera size={34}/>:<Mic size={34}/>}<strong>{fmt(elapsed)}</strong><small>{state==='recording'?'RECORDING':state==='paused'?'PAUSED':state==='preview'?'PREVIEW':'READY'}</small></div></div><div className="controls">{state==='idle'&&<button className="primary" onClick={start}><CircleStop size={18}/>Start {mode}</button>}{(state==='recording'||state==='paused')&&<><button className="primary" onClick={pause}>{state==='paused'?<Play size={18}/>:<Pause size={18}/>} {state==='paused'?'Resume':'Pause'}</button><button className="danger" onClick={()=>recorder.current?.stop()}><Square size={17}/>Stop</button></>}{state==='preview'&&<><button className="primary" onClick={save}><Save size={18}/>Save locally</button><button className="ghost" onClick={discard}><RotateCcw size={17}/>Discard</button></>}</div><div className="status-line"><span className={state==='recording'?'dot live':'dot'}/> {message}</div>{previewUrl&&<div className="preview">{mode==='video'?<video controls src={previewUrl}/>:<audio controls src={previewUrl}/>}<span>Preview only until you choose Save locally.</span></div>}</div>
 <aside className="recent-card"><div className="card-top"><div><span className="eyebrow">FIELD LIBRARY</span><h2>Evidence queue</h2></div><span className="sync-badge">LOCAL</span></div><p className="muted">Offline-ready. Nothing leaves this device until you choose an action.</p>{captures.length===0?<div className="empty">No saved evidence yet.<br/>Your next capture will appear here.</div>:<div className="capture-list">{captures.map(c=><div className="capture-row" key={c.id}><span className={`type-icon ${c.type}`}>{c.type==='video'?<Video size={16}/>:<Mic size={16}/>}</span><div className="capture-meta"><strong>{c.type==='video'?'Video + audio':'Audio note'}</strong><small>{new Date(c.createdAt).toLocaleString()} · {fmt(c.duration)}</small><div className="row-actions"><button onClick={()=>createAudit(c)}>Audit</button><button onClick={()=>sendReaper(c)}>Reaper</button><button className="discord" onClick={()=>notifyDiscord(c)}>Discord</button></div></div><span className="local-label">{c.status}</span></div>)}</div>}<div className="flow-card"><Cloud size={17}/><div><b>Controlled sync</b><span>Audit → AI extraction → Reaper → CRM → team alerts</span></div></div>{notice&&<div className="audit-success"><Check size={15}/>{notice}</div>}</aside></section></main>;
}
