import test from "node:test";
import assert from "node:assert/strict";
import { AuthService, parseCookies, publicUser } from "../server/auth/auth.js";
import { MemoryUserRepository } from "../server/auth/repositories.js";
import { createAuthRuntime } from "../server/auth/createAuthRuntime.js";

function runtime() { const repository = new MemoryUserRepository(); return { repository, service: new AuthService({ repository, secret: "test-secret-that-is-at-least-32-bytes-long", rounds: 4 }) }; }
test("registration hashes passwords and returns only public account fields", async () => { const { repository, service } = runtime(); const user = await service.register({ email: " Artist@Example.com ", password: "strong-passphrase", displayName: "Wise Artist" }); assert.equal(user.email, "artist@example.com"); assert.notEqual(user.passwordHash, "strong-passphrase"); assert.deepEqual(Object.keys(publicUser(user)), ["id", "email", "displayName", "createdAt"]); assert.equal(await repository.findByEmail("artist@example.com"), user); });
test("login verifies credentials and signed sessions", async () => { const { service } = runtime(); const user = await service.register({ email: "artist@example.com", password: "strong-passphrase", displayName: "Wise Artist" }); const loggedIn = await service.login({ email: "artist@example.com", password: "strong-passphrase" }); const payload = await service.verify(await service.issue(loggedIn)); assert.equal(payload.sub, user.id); await assert.rejects(() => service.login({ email: "artist@example.com", password: "wrong-password" }), /incorrect/); });
test("validation blocks weak passwords, invalid email, and duplicate accounts", async () => { const { service } = runtime(); await assert.rejects(() => service.register({ email: "bad", password: "strong-passphrase", displayName: "Name" }), /valid email/); await assert.rejects(() => service.register({ email: "a@b.com", password: "short", displayName: "Name" }), /10–72/); await service.register({ email: "a@b.com", password: "strong-passphrase", displayName: "Name" }); await assert.rejects(() => service.register({ email: "a@b.com", password: "another-strong-pass", displayName: "Name" }), /already exists/); });
test("user state is isolated by account", async () => { const { repository, service } = runtime(); const a = await service.register({ email: "a@b.com", password: "strong-passphrase", displayName: "Alpha" }); const b = await service.register({ email: "b@b.com", password: "strong-passphrase", displayName: "Beta" }); await repository.saveState(a.id, { favorites: { version: 2, items: [{ id: "one" }] }, assets: { version: 1, items: [] } }); assert.equal((await repository.getState(a.id)).favorites.items.length, 1); assert.equal((await repository.getState(b.id)).favorites.items.length, 0); });
test("cookie parser extracts signed session cookies", () => { assert.deepEqual(parseCookies("theme=dark; wt_session=abc.def; x=1"), { theme: "dark", wt_session: "abc.def", x: "1" }); });
test("production refuses ephemeral authentication configuration", () => { assert.throws(() => createAuthRuntime({ env: { NODE_ENV: "production" } }), /AUTH_SECRET/); assert.throws(() => createAuthRuntime({ env: { NODE_ENV: "production", AUTH_SECRET: "configured" } }), /DATABASE_URL/); });
test("video credits reserve atomically and never allow an unpaid balance", async () => { const { repository, service } = runtime(); const user = await service.register({ email:"credits@example.com", password:"strong-passphrase", displayName:"Credit Builder" }); assert.equal(await repository.getVideoCredits(user.id),0); await repository.grantVideoCredits(user.id,1); assert.equal(await repository.reserveVideoCredits(user.id,0.4),0.6); assert.equal(await repository.reserveVideoCredits(user.id,0.7),null); assert.equal(await repository.refundVideoCredits(user.id,0.4),1); });
test("image entitlement defaults to watermarked free access and can activate Pro", async () => { const { repository, service } = runtime(); const user = await service.register({ email:"pro@example.com", password:"strong-passphrase", displayName:"Pro Builder" }); assert.deepEqual(await repository.getImageEntitlement(user.id),{plan:"free",active:false,activeUntil:null,stripeCustomerId:null,stripeSubscriptionId:null,stripeStatus:null}); assert.deepEqual(await repository.setImageEntitlement(user.id,{plan:"pro",active:true}),{plan:"pro",active:true,activeUntil:null,stripeCustomerId:null,stripeSubscriptionId:null,stripeStatus:null}); });
