#!/bin/bash

# WISE² restic Backup Setup — Phase 2 OSS Toolkit
#
# Sets up encrypted, deduplicated, incremental backups of:
#   - PostgreSQL (all Docker Compose stacks: wise2_prod, glitchtip, infisical, langfuse)
#   - Key application directories (uploads, graphics, docker volumes, .env files)
#
# This script installs restic (if missing), initializes a restic repository,
# writes a daily backup runner to /usr/local/bin, and prints crontab instructions.
# It does NOT install the crontab entry automatically — review and add it manually
# (see "CRON SETUP" section printed at the end).
#
# Usage:
#   ./scripts/backup-setup.sh                # interactive first-time setup
#   RESTIC_REPOSITORY=... RESTIC_PASSWORD=... ./scripts/backup-setup.sh --non-interactive
#
# Reuses conventions from scripts/backup-database.sh (log format, env var overrides).

set -euo pipefail

# ---------------------------------------------------------------------------
# Config (override via environment or .env.production before running)
# ---------------------------------------------------------------------------
BACKUP_ROOT="${BACKUP_ROOT:-/backups/wise2-restic}"
RESTIC_REPOSITORY="${RESTIC_REPOSITORY:-/backups/wise2-restic/repo}"   # or s3:https://... / b2:bucket:path / sftp:user@host:/path
RESTIC_PASSWORD_FILE="${RESTIC_PASSWORD_FILE:-/etc/wise2/restic-password}"
RETENTION_DAILY="${RETENTION_DAILY:-14}"
RETENTION_WEEKLY="${RETENTION_WEEKLY:-8}"
RETENTION_MONTHLY="${RETENTION_MONTHLY:-6}"

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"

# Databases to dump before snapshotting (container_name:db_name:db_user pairs)
DATABASES=(
  "wise2-db:wise2_prod:wise2"
  "wise2-glitchtip-db:glitchtip:glitchtip"
  "wise2-infisical-db:infisical:infisical"
  "wise2-langfuse-db:langfuse:langfuse"
)

# App directories to include in every snapshot (adjust paths to actual host mounts)
BACKUP_PATHS=(
  "/home/dwise/wise2-core/.env.production"
  "/home/dwise/wise2-core/certs"
  "/var/lib/docker/volumes/wise2-core_postgres_data"
  "/var/lib/docker/volumes/wise2-core_graphics_data"
  "$BACKUP_ROOT/db-dumps"
)

RUNNER_PATH="/usr/local/bin/wise2-restic-backup.sh"

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# ---------------------------------------------------------------------------
# 1. Install restic if missing
# ---------------------------------------------------------------------------
if ! command -v restic >/dev/null 2>&1; then
  log "restic not found — installing..."
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install -y restic
  elif command -v brew >/dev/null 2>&1; then
    brew install restic
  else
    log "No supported package manager found. Install restic manually: https://restic.net/"
    exit 1
  fi
else
  log "restic already installed: $(restic version)"
fi

# ---------------------------------------------------------------------------
# 2. Ensure password file exists (never commit this file or its contents)
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$RESTIC_PASSWORD_FILE")"
if [ ! -f "$RESTIC_PASSWORD_FILE" ]; then
  log "Generating new restic repository password at $RESTIC_PASSWORD_FILE"
  openssl rand -base64 48 > "$RESTIC_PASSWORD_FILE"
  chmod 600 "$RESTIC_PASSWORD_FILE"
  log "IMPORTANT: back up $RESTIC_PASSWORD_FILE somewhere off-server (password manager)."
  log "Losing this file makes ALL existing backups permanently unrecoverable."
else
  log "Using existing restic password file: $RESTIC_PASSWORD_FILE"
fi

mkdir -p "$BACKUP_ROOT/db-dumps"

# ---------------------------------------------------------------------------
# 3. Initialize restic repository (idempotent — no-ops if already initialized)
# ---------------------------------------------------------------------------
export RESTIC_REPOSITORY
export RESTIC_PASSWORD_FILE

if ! restic snapshots >/dev/null 2>&1; then
  log "Initializing restic repository at $RESTIC_REPOSITORY"
  restic init
else
  log "restic repository already initialized at $RESTIC_REPOSITORY"
fi

# ---------------------------------------------------------------------------
# 4. Write the daily backup runner
# ---------------------------------------------------------------------------
log "Writing backup runner to $RUNNER_PATH"
sudo tee "$RUNNER_PATH" > /dev/null <<RUNNER_EOF
#!/bin/bash
# Auto-generated by scripts/backup-setup.sh — do not edit by hand, re-run setup instead.
set -euo pipefail

export RESTIC_REPOSITORY="$RESTIC_REPOSITORY"
export RESTIC_PASSWORD_FILE="$RESTIC_PASSWORD_FILE"

BACKUP_ROOT="$BACKUP_ROOT"
LOG_FILE="\$BACKUP_ROOT/backup.log"
mkdir -p "\$BACKUP_ROOT/db-dumps"

log() {
  echo "[\$(date +'%Y-%m-%d %H:%M:%S')] \$*" >> "\$LOG_FILE"
}

log "=== Starting WISE² restic backup ==="

# --- Dump each Postgres database from its running container ---
$(for entry in "${DATABASES[@]}"; do
  IFS=':' read -r container dbname dbuser <<< "$entry"
  cat <<DUMP_EOF
if docker inspect "$container" >/dev/null 2>&1; then
  DUMP_FILE="\$BACKUP_ROOT/db-dumps/${dbname}_\$(date +%Y%m%d_%H%M%S).sql.gz"
  if docker exec "$container" pg_dump -U "$dbuser" "$dbname" 2>>"\$LOG_FILE" | gzip > "\$DUMP_FILE"; then
    log "Dumped $dbname -> \$DUMP_FILE"
  else
    log "WARNING: pg_dump failed for $dbname (container may be down)"
  fi
else
  log "Skipping $dbname — container $container not running"
fi
DUMP_EOF
done)

# Keep only the last 3 local dumps per DB (restic retains full history remotely)
find "\$BACKUP_ROOT/db-dumps" -name "*.sql.gz" -mtime +3 -delete

# --- Snapshot app directories + fresh DB dumps into restic ---
if restic backup \\
$(for p in "${BACKUP_PATHS[@]}"; do echo "  \"$p\" \\"; done)
  --tag wise2-daily \\
  >> "\$LOG_FILE" 2>&1; then
  log "restic backup completed successfully"
else
  log "ERROR: restic backup failed — check \$LOG_FILE"
  exit 1
fi

# --- Prune old snapshots per retention policy ---
restic forget \\
  --keep-daily $RETENTION_DAILY \\
  --keep-weekly $RETENTION_WEEKLY \\
  --keep-monthly $RETENTION_MONTHLY \\
  --prune \\
  >> "\$LOG_FILE" 2>&1

log "=== Backup + prune complete ==="
RUNNER_EOF

sudo chmod 700 "$RUNNER_PATH"
log "Runner installed at $RUNNER_PATH (mode 700)"

# ---------------------------------------------------------------------------
# 5. Print cron setup instructions (NOT installed automatically)
# ---------------------------------------------------------------------------
cat <<CRON_EOF

=======================================================================
CRON SETUP — add this line with 'crontab -e' (runs daily at 02:00 UTC,
matching the documented DB backup schedule in CLAUDE.md):

0 2 * * * $RUNNER_PATH >> $BACKUP_ROOT/cron.log 2>&1

Verify after first run:
  restic snapshots
  restic stats latest
  tail -f $BACKUP_ROOT/backup.log

Restore example (single file):
  restic restore latest --target /tmp/restore-test --include /home/dwise/wise2-core/.env.production

Restore example (full snapshot):
  restic restore <snapshot-id> --target /restore-dir
=======================================================================
CRON_EOF

log "Setup complete."
