#!/usr/bin/env bash
set -euo pipefail
root_dir="$(cd "$(dirname "$0")/.." && pwd)"
service_dir="$root_dir/services/discord-ecosystem"
env_file="${WISE2_DISCORD_ENV_FILE:-$service_dir/.env}"
if [[ ! -f "$env_file" ]]; then cp "$service_dir/.env.example" "$env_file"; chmod 600 "$env_file"; echo "Created $env_file. Add Discord values, then rerun."; exit 2; fi
source "$env_file"
missing=0
for key in GUILD_ID; do if [[ -z "${!key:-}" ]]; then echo "Missing $key"; missing=1; fi; done
for key in EXECUTIVE REAPER STUDIO_SESSION MIX_REVIEW; do token_key="${key}_BOT_TOKEN"; client_key="${key}_CLIENT_ID"; if [[ -z "${!token_key:-}" ]]; then echo "Missing $token_key"; missing=1; fi; if [[ -z "${!client_key:-}" ]]; then echo "Missing $client_key"; missing=1; fi; done
if (( missing )); then echo "Populate $env_file; no secrets are generated by this script."; exit 2; fi
echo "WISE² Discord configuration is complete for core, REAPER, session, and mix-review bots."
echo "Invite URLs:"
for key in EXECUTIVE REAPER STUDIO_SESSION MIX_REVIEW; do client_key="${key}_CLIENT_ID"; echo "https://discord.com/oauth2/authorize?client_id=${!client_key}&scope=bot%20applications.commands&permissions=2147485696"; done
echo "Run: pnpm --dir services/discord-ecosystem build && pnpm --dir services/discord-ecosystem start"
