import { createAuditEvent } from './audit/events.ts';
import type { Catalog } from './conversations/queue.ts';
import { emptySignals } from './priority/score.ts';
import type {
  Conversation,
  Customer,
  Equipment,
  Location,
  Opportunity,
  ServiceEvent,
  Technician,
  TranscriptLine,
} from './types.ts';

export const SIMULATION_NOW = '2026-08-30T21:46:00.000Z';
export const BUSINESS_NAME = 'WISE² Home Services';
export const OPERATING_STATUS = 'Simulation desk open';

export const TECHNICIANS: Technician[] = [
  { id: 'tech-rivera', name: 'Maya Rivera', trade: 'HVAC', availableToday: true },
  { id: 'tech-owens', name: 'Chris Owens', trade: 'Electrical', availableToday: true },
  { id: 'tech-patel', name: 'Asha Patel', trade: 'Plumbing', availableToday: false },
];

const lines = (rows: Array<[TranscriptLine['speaker'], string, string]>): TranscriptLine[] =>
  rows.map(([speaker, at, text]) => ({ speaker, at, text }));

const customers: Customer[] = [
  {
    id: 'cust-harlow',
    name: 'Eleanor Harlow',
    phone: '+15520140001',
    email: 'eleanor.harlow@example.test',
    flags: ['existing', 'elderly occupant'],
    preferredContactMethod: 'phone',
  },
  {
    id: 'cust-briggs',
    name: 'Noah Briggs',
    phone: '+15520140002',
    email: 'noah.briggs@example.test',
    flags: ['existing'],
    preferredContactMethod: 'sms',
  },
  {
    id: 'cust-okonkwo',
    name: 'Ada Okonkwo',
    phone: '+15520140003',
    email: 'ada.okonkwo@example.test',
    flags: ['existing'],
    preferredContactMethod: 'phone',
  },
  {
    id: 'cust-mendez',
    name: 'Luis Mendez',
    phone: '+15520140004',
    email: 'luis.mendez@example.test',
    flags: ['existing'],
    preferredContactMethod: 'phone',
  },
  {
    id: 'cust-vale',
    name: 'Priya Vale',
    phone: '+15520140005',
    email: 'priya.vale@example.test',
    flags: ['new lead'],
    preferredContactMethod: 'email',
  },
  {
    id: 'cust-ross',
    name: 'Helen Ross',
    phone: '+15520140006',
    email: 'helen.ross@example.test',
    flags: ['existing'],
    preferredContactMethod: 'email',
  },
  {
    id: 'cust-cho',
    name: 'Grace Cho',
    phone: '+15520140007',
    email: 'grace.cho@example.test',
    flags: ['existing'],
    preferredContactMethod: 'sms',
  },
  {
    id: 'cust-bennett',
    name: 'Owen Bennett',
    phone: '+15520140008',
    email: 'owen.bennett@example.test',
    flags: ['existing'],
    preferredContactMethod: 'phone',
  },
];

const locations: Location[] = [
  {
    id: 'loc-harlow',
    customerId: 'cust-harlow',
    address: '418 Maple Court, Durham, NC',
    indoorCondition: '88°F indoors, stagnant air, occupant reporting dizziness',
    accessNotes: 'Side gate unlocked. Elderly resident may need extra time at the door.',
  },
  {
    id: 'loc-briggs',
    customerId: 'cust-briggs',
    address: '902 Cedar Run, Raleigh, NC',
    indoorCondition: 'Water crossing hallway toward living room',
    accessNotes: 'Shutoff valve behind washer. Dog in crate.',
  },
  {
    id: 'loc-okonkwo',
    customerId: 'cust-okonkwo',
    address: '15 Birch Lane, Cary, NC',
    indoorCondition: 'Burning odor near panel. Occupants waiting outside.',
    accessNotes: 'Main panel in garage. Do not restore power until inspected.',
  },
  {
    id: 'loc-mendez',
    customerId: 'cust-mendez',
    address: '77 Pinecrest Ave, Chapel Hill, NC',
    indoorCondition: 'Intermittent cooling, 79°F at last callback',
    accessNotes: 'Attic pull-down stairs. Park in driveway.',
  },
  {
    id: 'loc-vale',
    customerId: 'cust-vale',
    address: '2200 Lake Ridge Rd, Apex, NC',
    indoorCondition: 'Working but aging system, owner planning replacement',
    accessNotes: 'New construction HOA. Use visitor pass on mailbox.',
  },
  {
    id: 'loc-ross',
    customerId: 'cust-ross',
    address: '6 Willow Place, Morrisville, NC',
    indoorCondition: null,
    accessNotes: null,
  },
  {
    id: 'loc-cho',
    customerId: 'cust-cho',
    address: '881 Oak Hill, Wake Forest, NC',
    indoorCondition: 'Comfortable, scheduled maintenance window',
    accessNotes: 'Lockbox on gas meter. Code in CRM.',
  },
  {
    id: 'loc-bennett',
    customerId: 'cust-bennett',
    address: '44 Riverbend Ct, Holly Springs, NC',
    indoorCondition: 'Drywall repaired after prior leak',
    accessNotes: null,
  },
];

const equipment: Equipment[] = [
  {
    id: 'eq-harlow',
    locationId: 'loc-harlow',
    category: 'Split heat pump',
    manufacturer: 'Carrier',
    model: '25HBC536A003',
    serial: 'SIM-HP-4418',
    ageYears: 11,
    warrantyStatus: 'Parts expired',
  },
  {
    id: 'eq-briggs',
    locationId: 'loc-briggs',
    category: 'Water heater',
    manufacturer: 'Rheem',
    model: 'XE50M06ST45U1',
    serial: 'SIM-WH-0902',
    ageYears: 8,
    warrantyStatus: 'Out of warranty',
  },
  {
    id: 'eq-okonkwo',
    locationId: 'loc-okonkwo',
    category: 'Main electrical panel',
    manufacturer: 'Square D',
    model: 'QO142M200PC',
    serial: null,
    ageYears: 19,
    warrantyStatus: 'Unavailable',
  },
  {
    id: 'eq-mendez',
    locationId: 'loc-mendez',
    category: 'Air conditioner',
    manufacturer: 'Trane',
    model: 'XR14',
    serial: 'SIM-AC-0077',
    ageYears: 7,
    warrantyStatus: 'Labor expired',
  },
  {
    id: 'eq-vale',
    locationId: 'loc-vale',
    category: 'Gas furnace',
    manufacturer: 'Lennox',
    model: 'EL296UH090XV36B',
    serial: 'SIM-FN-2200',
    ageYears: 16,
    warrantyStatus: 'Expired',
  },
  {
    id: 'eq-ross',
    locationId: 'loc-ross',
    category: 'Unavailable',
    manufacturer: null,
    model: null,
    serial: null,
    ageYears: null,
    warrantyStatus: null,
  },
  {
    id: 'eq-cho',
    locationId: 'loc-cho',
    category: 'Package unit',
    manufacturer: 'Goodman',
    model: 'GPC1460H41',
    serial: 'SIM-PK-0881',
    ageYears: 4,
    warrantyStatus: 'In warranty',
  },
  {
    id: 'eq-bennett',
    locationId: 'loc-bennett',
    category: 'Supply line',
    manufacturer: 'Unavailable',
    model: null,
    serial: null,
    ageYears: null,
    warrantyStatus: null,
  },
];

const serviceEvents: ServiceEvent[] = [
  {
    id: 'svc-harlow-1',
    customerId: 'cust-harlow',
    equipmentId: 'eq-harlow',
    occurredAt: '2026-06-12T15:00:00.000Z',
    type: 'repair',
    summary: 'Compressor hard-start kit after no-cool callback',
    outcome: 'Cooling restored temporarily; compressor noise documented',
  },
  {
    id: 'svc-harlow-2',
    customerId: 'cust-harlow',
    equipmentId: 'eq-harlow',
    occurredAt: '2025-08-03T14:00:00.000Z',
    type: 'maintenance',
    summary: 'Cooling tune-up and capacitor check',
    outcome: 'Passed; recommended compressor watch',
  },
  {
    id: 'svc-briggs-1',
    customerId: 'cust-briggs',
    equipmentId: 'eq-briggs',
    occurredAt: '2026-01-19T18:20:00.000Z',
    type: 'repair',
    summary: 'T&P discharge drip, replaced valve',
    outcome: 'Leak stopped; tank age noted',
  },
  {
    id: 'svc-okonkwo-1',
    customerId: 'cust-okonkwo',
    equipmentId: 'eq-okonkwo',
    occurredAt: '2024-11-02T13:10:00.000Z',
    type: 'inspection',
    summary: 'Panel tightness and labeling after renovation',
    outcome: 'No faults found; lugs re-torqued',
  },
  {
    id: 'svc-mendez-1',
    customerId: 'cust-mendez',
    equipmentId: 'eq-mendez',
    occurredAt: '2026-07-21T16:40:00.000Z',
    type: 'diagnostic',
    summary: 'Intermittent cooling, dirty coil clean',
    outcome: 'Performance improved; callback window offered',
  },
  {
    id: 'svc-cho-1',
    customerId: 'cust-cho',
    equipmentId: 'eq-cho',
    occurredAt: '2026-08-30T13:00:00.000Z',
    type: 'maintenance',
    summary: 'Same-day package-unit tune-up booked',
    outcome: 'Scheduled 4:00 PM window',
  },
  {
    id: 'svc-bennett-1',
    customerId: 'cust-bennett',
    equipmentId: 'eq-bennett',
    occurredAt: '2026-08-28T19:15:00.000Z',
    type: 'repair',
    summary: 'Supply-line leak isolated and replaced',
    outcome: 'Completed; drywall referred out',
  },
];

const conversations: Conversation[] = [
  {
    id: 'conv-harlow-nocoool',
    channel: 'phone',
    direction: 'inbound',
    receivedAt: '2026-08-30T19:12:00.000Z',
    status: 'new',
    priorityOverride: null,
    customerId: 'cust-harlow',
    issue: 'No cooling, 88°F indoors',
    customerStatement: 'The air has been dead since noon and it is 88 degrees in here. I am 79 and starting to feel light-headed.',
    summary:
      'Existing HVAC customer reports total loss of cooling with 88°F indoor temperature and an elderly occupant. Prior compressor work increases repeat-failure risk.',
    detectedSignals: emptySignals({
      immediateSafety: true,
      completeLossEssential: true,
      vulnerableOccupant: true,
      existingCustomer: true,
      repeatFailure: true,
      sameDayAvailability: true,
      highOpportunityPoints: 8,
    }),
    transcript: lines([
      ['system', '2026-08-30T19:12:00.000Z', 'Inbound call captured. Simulated transcript.'],
      ['agent', '2026-08-30T19:12:08.000Z', 'WISE² Home Services, this is the after-hours line. Are you safe?'],
      ['customer', '2026-08-30T19:12:16.000Z', 'The air has been dead since noon and it is 88 degrees in here.'],
      ['customer', '2026-08-30T19:12:28.000Z', 'I am 79 and starting to feel light-headed. The unit outside is silent.'],
      ['agent', '2026-08-30T19:12:40.000Z', 'I am going to get this in front of a dispatcher. If you feel worse, call emergency services. We are not an emergency provider.'],
    ]),
  },
  {
    id: 'conv-briggs-leak',
    channel: 'phone',
    direction: 'inbound',
    receivedAt: '2026-08-30T19:48:00.000Z',
    status: 'needs_review',
    priorityOverride: null,
    customerId: 'cust-briggs',
    issue: 'Active water heater leak',
    customerStatement: 'The water heater is dumping onto the laundry floor and it is already at the hallway.',
    summary: 'Active plumbing leak with spreading water and prior T&P work. Property-damage risk is rising.',
    detectedSignals: emptySignals({
      activePropertyDamage: true,
      completeLossEssential: true,
      existingCustomer: true,
      repeatFailure: true,
      highOpportunityPoints: 6,
    }),
    transcript: lines([
      ['system', '2026-08-30T19:48:00.000Z', 'Inbound call captured. Simulated transcript.'],
      ['customer', '2026-08-30T19:48:10.000Z', 'The water heater is dumping onto the laundry floor and it is already at the hallway.'],
      ['agent', '2026-08-30T19:48:22.000Z', 'If you can reach it safely, shut the water valve behind the washer. Do not enter standing water if you see sparks.'],
    ]),
  },
  {
    id: 'conv-okonkwo-electrical',
    channel: 'phone',
    direction: 'inbound',
    receivedAt: '2026-08-30T20:05:00.000Z',
    status: 'new',
    priorityOverride: null,
    customerId: 'cust-okonkwo',
    issue: 'Electrical burning smell',
    customerStatement: 'There is a burning smell at the garage panel. We are outside. Please send someone now.',
    summary:
      'Burning odor at the main panel. Immediate human escalation is required. WISE² is not an emergency-service provider.',
    detectedSignals: emptySignals({
      immediateSafety: true,
      activePropertyDamage: true,
      completeLossEssential: true,
      existingCustomer: true,
    }),
    transcript: lines([
      ['system', '2026-08-30T20:05:00.000Z', 'Inbound call captured. Simulated transcript.'],
      ['customer', '2026-08-30T20:05:09.000Z', 'There is a burning smell at the garage panel. We are outside.'],
      ['agent', '2026-08-30T20:05:18.000Z', 'Stay outside. If you see smoke or flame, call emergency services. I am escalating this to a human dispatcher now.'],
    ]),
  },
  {
    id: 'conv-mendez-callback',
    channel: 'sms',
    direction: 'inbound',
    receivedAt: '2026-08-30T17:30:00.000Z',
    status: 'callback_due',
    priorityOverride: null,
    customerId: 'cust-mendez',
    issue: 'Intermittent cooling callback',
    customerStatement: 'It cooled for an hour after the last visit and then quit again. Can someone call me today?',
    summary: 'Existing HVAC customer requesting a same-day callback for intermittent cooling after a July coil clean.',
    detectedSignals: emptySignals({
      existingCustomer: true,
      sameDayAvailability: true,
      highOpportunityPoints: 4,
    }),
    transcript: lines([
      ['system', '2026-08-30T17:30:00.000Z', 'Inbound SMS captured. Simulated transcript.'],
      ['customer', '2026-08-30T17:30:04.000Z', 'It cooled for an hour after the last visit and then quit again. Can someone call me today?'],
    ]),
  },
  {
    id: 'conv-vale-replace',
    channel: 'web',
    direction: 'inbound',
    receivedAt: '2026-08-30T16:05:00.000Z',
    status: 'new',
    priorityOverride: null,
    customerId: 'cust-vale',
    issue: 'Replacement estimate request',
    customerStatement: 'Our 16-year furnace is getting loud. We want a replacement estimate this week, not an emergency.',
    summary: 'New lead requested a furnace replacement estimate. No safety or outage signals.',
    detectedSignals: emptySignals({
      highOpportunityPoints: 10,
    }),
    transcript: lines([
      ['system', '2026-08-30T16:05:00.000Z', 'Web form captured. Simulated transcript.'],
      ['customer', '2026-08-30T16:05:00.000Z', 'Our 16-year furnace is getting loud. We want a replacement estimate this week, not an emergency.'],
    ]),
  },
  {
    id: 'conv-ross-invoice',
    channel: 'email',
    direction: 'inbound',
    receivedAt: '2026-08-30T15:10:00.000Z',
    status: 'new',
    priorityOverride: null,
    customerId: 'cust-ross',
    issue: 'Invoice copy request',
    customerStatement: 'Please email a copy of last month’s invoice for my records.',
    summary: 'Routine administrative request for an invoice copy. No service emergency.',
    detectedSignals: emptySignals({
      existingCustomer: true,
      routineAdministrative: true,
    }),
    transcript: lines([
      ['system', '2026-08-30T15:10:00.000Z', 'Inbound email captured. Simulated transcript.'],
      ['customer', '2026-08-30T15:10:00.000Z', 'Please email a copy of last month’s invoice for my records.'],
    ]),
  },
  {
    id: 'conv-cho-scheduled',
    channel: 'phone',
    direction: 'inbound',
    receivedAt: '2026-08-30T13:00:00.000Z',
    status: 'scheduled',
    priorityOverride: null,
    customerId: 'cust-cho',
    issue: 'Package-unit tune-up',
    customerStatement: 'Just confirming the 4 PM maintenance window. Gate code is in the file.',
    summary: 'Existing customer already booked for a same-day package-unit tune-up.',
    detectedSignals: emptySignals({
      existingCustomer: true,
      sameDayAvailability: true,
      alreadyScheduledOrResolved: true,
      highOpportunityPoints: 3,
    }),
    transcript: lines([
      ['system', '2026-08-30T13:00:00.000Z', 'Inbound call captured. Simulated transcript.'],
      ['customer', '2026-08-30T13:00:12.000Z', 'Just confirming the 4 PM maintenance window. Gate code is in the file.'],
    ]),
  },
  {
    id: 'conv-bennett-done',
    channel: 'phone',
    direction: 'inbound',
    receivedAt: '2026-08-28T18:40:00.000Z',
    status: 'completed',
    priorityOverride: null,
    customerId: 'cust-bennett',
    issue: 'Supply-line leak repaired',
    customerStatement: 'Thank you. The floor is dry and we will handle drywall separately.',
    summary: 'Completed leak repair. Retained for search, filters, and audit history.',
    detectedSignals: emptySignals({
      existingCustomer: true,
      alreadyScheduledOrResolved: true,
    }),
    transcript: lines([
      ['system', '2026-08-28T18:40:00.000Z', 'Inbound call captured. Simulated transcript.'],
      ['customer', '2026-08-28T19:20:00.000Z', 'Thank you. The floor is dry and we will handle drywall separately.'],
    ]),
  },
];

const opportunities: Opportunity[] = [
  { conversationId: 'conv-harlow-nocoool', lowEstimate: 28000, highEstimate: 620000, confidence: 'medium' },
  { conversationId: 'conv-briggs-leak', lowEstimate: 22000, highEstimate: 240000, confidence: 'medium' },
  { conversationId: 'conv-okonkwo-electrical', lowEstimate: 18000, highEstimate: 190000, confidence: 'low' },
  { conversationId: 'conv-mendez-callback', lowEstimate: 16000, highEstimate: 90000, confidence: 'medium' },
  { conversationId: 'conv-vale-replace', lowEstimate: 680000, highEstimate: 1240000, confidence: 'high' },
  { conversationId: 'conv-ross-invoice', lowEstimate: 0, highEstimate: 0, confidence: 'low' },
  { conversationId: 'conv-cho-scheduled', lowEstimate: 18900, highEstimate: 18900, confidence: 'high' },
  { conversationId: 'conv-bennett-done', lowEstimate: 42000, highEstimate: 42000, confidence: 'high' },
];

export function createSeedCatalog(): Catalog {
  return {
    conversations: structuredClone(conversations),
    customers: structuredClone(customers),
    locations: structuredClone(locations),
    equipment: structuredClone(equipment),
    serviceEvents: structuredClone(serviceEvents),
    opportunities: structuredClone(opportunities),
    actions: [],
    audit: [
      createAuditEvent({
        action: 'conversation.captured',
        objectType: 'conversation',
        objectId: 'conv-harlow-nocoool',
        timestamp: '2026-08-30T19:12:00.000Z',
        metadata: { channel: 'phone', simulated: 'true' },
      }),
      createAuditEvent({
        action: 'conversation.captured',
        objectType: 'conversation',
        objectId: 'conv-cho-scheduled',
        timestamp: '2026-08-30T13:00:00.000Z',
        metadata: { channel: 'phone', simulated: 'true' },
      }),
      createAuditEvent({
        action: 'conversation.completed',
        objectType: 'conversation',
        objectId: 'conv-bennett-done',
        timestamp: '2026-08-28T19:20:00.000Z',
        metadata: { simulated: 'true' },
      }),
    ],
  };
}

export const SEED_NOTICE =
  'Seeded simulation data. No live phone, CRM, dispatch, messaging, estimating, or payment systems are connected.';
