'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { useEffect, useState } from 'react';
import { getBlakkhailProducts } from '@/lib/sencere-products';
import { productPath } from '@/lib/site-domains';
import { BLAKKHAIL_LEGACY } from '@/lib/sencere/blakkhail-legacy';
import { BLAKKHAIL, BLAKKHAIL_LAYOUT } from './brand-tokens';

export function BlakkhailStorefront() {
  const [host, setHost] = useState<string | null>(null);
  const products = getBlakkhailProducts();
  const hero = BLAKKHAIL_LEGACY.assets.heroPhotos;
  const shop = BLAKKHAIL_LEGACY.assets.shopPhotos;
  useEffect(() => setHost(window.location.hostname), []);
  return <>
    <section id="home" className="border-b" style={{ borderColor: BLAKKHAIL.neutral200 }}><div className="relative min-h-[72vh] overflow-hidden bg-neutral-100 md:min-h-[84vh]"><Image src={hero[0]} alt="Blakk Hail collection by SenCere Creative LLC" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 mx-auto flex w-full max-w-[1400px] items-end justify-between px-5 pb-8 text-white sm:px-8 sm:pb-12 lg:px-12"><div><p className="mb-3 text-[10px] uppercase tracking-[0.38em] text-white/75">A SenCere Creative LLC brand · 2026</p><h1 className="max-w-5xl text-5xl font-black uppercase leading-[.86] tracking-[-.045em] sm:text-7xl lg:text-[8rem]" style={{ fontFamily: 'Arial Black, Arial, Helvetica, sans-serif' }}>Blakk Hail</h1></div><a href="#shop" className="hidden items-center gap-2 border-b border-white pb-1 text-xs uppercase tracking-[0.2em] sm:flex">Explore collection <ArrowUpRight size={15} /></a></div></div></section>
    <section className="border-b py-16 sm:py-24" style={{ borderColor: BLAKKHAIL.neutral200 }}><div className={`${BLAKKHAIL_LAYOUT.container} grid gap-8 md:grid-cols-[1fr_1.5fr] md:gap-20`}><p className="text-[10px] uppercase tracking-[0.3em]" style={{ color: BLAKKHAIL.neutral600 }}>01 / The brand</p><div><h2 className="max-w-3xl text-3xl font-medium uppercase leading-[.95] tracking-[-.035em] sm:text-5xl" style={{ fontFamily: 'var(--font-display)' }}>Original fashion for people who move differently.</h2><p className="mt-8 max-w-xl text-sm leading-7" style={{ color: BLAKKHAIL.neutral600 }}>Blakk Hail is independent streetwear rooted in self-expression, design, and the everyday uniform. Made in the city. Worn everywhere.</p><a href="#about" className="mt-8 inline-flex items-center gap-2 border-b pb-1 text-xs uppercase tracking-[0.18em]">Read our story <ArrowUpRight size={14} /></a></div></div></section>
    <section id="shop" className={`${BLAKKHAIL_LAYOUT.container} py-14 sm:py-20`}><div className="mb-8 flex items-end justify-between border-b pb-4" style={{ borderColor: BLAKKHAIL.darkGold }}><div><p className="text-[10px] uppercase tracking-[0.3em]" style={{ color: BLAKKHAIL.steel }}>02 / Shop</p><h2 className="mt-3 text-3xl uppercase tracking-[-.03em] sm:text-5xl" style={{ color: BLAKKHAIL.gold, fontFamily: 'var(--font-display)' }}>The essentials</h2></div><span className="hidden text-xs uppercase tracking-[0.18em] sm:block">{products.length} pieces</span></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:gap-x-6 lg:grid-cols-3">{products.map((product, index) => <Link key={product.id} href={productPath(product.slug, host)} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-[#2A2A2A]"><Image src={product.image || shop[index % shop.length]} alt={product.name} fill sizes="(max-width: 640px) 50vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.035]" /></div><div className="flex items-start justify-between gap-3 pt-3 text-xs uppercase tracking-[0.08em]" style={{ color: BLAKKHAIL.steel }}><span>{product.name}</span><span>${product.basePrice.toFixed(2)}</span></div></Link>)}</div></section>
    <section id="look-book" className="border-y" style={{ borderColor: BLAKKHAIL.darkGold, backgroundColor: BLAKKHAIL.gunmetal }}><div className="grid md:grid-cols-2"><div className="relative min-h-[55vh]"><Image src={hero[1]} alt="Blakk Hail look book" fill sizes="50vw" className="object-cover" /></div><div className="flex flex-col justify-between p-6 sm:p-12 lg:p-20"><p className="text-[10px] uppercase tracking-[0.3em]" style={{ color: BLAKKHAIL.steel }}>03 / Look book</p><h2 className="max-w-md text-5xl uppercase leading-[.9] tracking-[-.04em] sm:text-7xl" style={{ color: BLAKKHAIL.gold, fontFamily: 'var(--font-display)' }}>Take control.<br />No apologies.</h2><a href="#contact" className="mt-12 flex items-center justify-between border-b pb-3 text-xs uppercase tracking-[0.18em]" style={{ borderColor: BLAKKHAIL.gold, color: BLAKKHAIL.steel }}>Connect with Blakk Hail <ArrowUpRight size={15} /></a></div></div></section>
    <section id="about" className="py-16 sm:py-24"><div className={`${BLAKKHAIL_LAYOUT.container} text-center`}><p className="text-[10px] uppercase tracking-[0.3em]" style={{ color: BLAKKHAIL.neutral600 }}>Blakk Hail · A SenCere Creative LLC brand</p><h2 className="mx-auto mt-6 max-w-4xl text-4xl uppercase leading-[.92] tracking-[-.04em] sm:text-7xl" style={{ fontFamily: 'var(--font-display)' }}>Design. Create.<br />Produce. Deliver.</h2></div></section>
  </>;
}
