import { BadRequestException, Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { google } from 'googleapis';
import { OAuthCredentialsRepository } from '../db/oauth-credentials.repository';
import { OAuthProvider } from '../db/oauth-credentials.entity';

@Injectable()
export class CjaysGoogleService {
  private readonly scopes = ['openid','email','https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/drive.file','https://www.googleapis.com/auth/gmail.send'];
  constructor(private readonly config: ConfigService, private readonly jwt: JwtService, private readonly credentials: OAuthCredentialsRepository) {}
  private oauthClient(){return new google.auth.OAuth2(this.config.get('GOOGLE_CLIENT_ID'),this.config.get('GOOGLE_CLIENT_SECRET'),this.config.get('CJAYS_GOOGLE_REDIRECT_URI')||`${this.config.get('APP_URL')||'http://localhost:3001'}/api/v1/cjays/google/callback`);}
  async status(userId:string){const value=await this.credentials.getCredentials(userId,OAuthProvider.GOOGLE);return {connected:!!value?.is_active,accountName:value?.account_name,scopes:value?.scopes?.split(' ')??[]};}
  authorize(userId:string,tenantId:string){if(!this.config.get('GOOGLE_CLIENT_ID')||!this.config.get('GOOGLE_CLIENT_SECRET'))throw new BadRequestException('Google Workspace is not configured');const state=this.jwt.sign({sub:userId,tenantId,purpose:'cjays-google'},{expiresIn:'10m'});return {authUrl:this.oauthClient().generateAuthUrl({access_type:'offline',prompt:'consent',scope:this.scopes,state,include_granted_scopes:true})};}
  async callback(code:string,state:string){let payload:any;try{payload=this.jwt.verify(state);}catch{throw new UnauthorizedException('Invalid or expired Google connection state');}if(payload.purpose!=='cjays-google')throw new UnauthorizedException('Invalid Google connection state');const oauth=this.oauthClient();const {tokens}=await oauth.getToken(code);if(!tokens.access_token)throw new BadRequestException('Google did not return an access token');oauth.setCredentials(tokens);const about=await google.oauth2({version:'v2',auth:oauth}).userinfo.get();await this.credentials.upsertCredentials(payload.sub,OAuthProvider.GOOGLE,{accessToken:tokens.access_token,refreshToken:tokens.refresh_token||undefined,tokenType:tokens.token_type||'Bearer',scopes:tokens.scope||this.scopes.join(' '),expiresAt:new Date(tokens.expiry_date||Date.now()+3600000),providerAccountId:about.data.id||undefined,accountName:about.data.email||undefined});return {connected:true,accountName:about.data.email};}
  private async auth(userId:string){const value=await this.credentials.getCredentials(userId,OAuthProvider.GOOGLE);if(!value?.is_active)throw new UnauthorizedException('Connect Google Workspace first');const oauth=this.oauthClient();oauth.setCredentials({access_token:value.access_token,refresh_token:value.refresh_token,expiry_date:value.expires_at.getTime()});oauth.on('tokens',async(tokens)=>{if(tokens.access_token)await this.credentials.updateToken(userId,OAuthProvider.GOOGLE,{accessToken:tokens.access_token,refreshToken:tokens.refresh_token||undefined,expiresAt:new Date(tokens.expiry_date||Date.now()+3600000),scopes:tokens.scope});});return oauth;}
  private approve(value:boolean){if(value!==true)throw new BadRequestException('Explicit approval is required for external Google actions');}
  async calendar(userId:string,input:{approved:boolean;title:string;description?:string;startTime:string;endTime:string;timezone?:string}){this.approve(input.approved);const auth=await this.auth(userId);const result=await google.calendar({version:'v3',auth}).events.insert({calendarId:'primary',conferenceDataVersion:1,requestBody:{summary:input.title,description:input.description,start:{dateTime:input.startTime,timeZone:input.timezone||'America/New_York'},end:{dateTime:input.endTime,timeZone:input.timezone||'America/New_York'},conferenceData:{createRequest:{requestId:crypto.randomUUID(),conferenceSolutionKey:{type:'hangoutsMeet'}}}}});return {eventId:result.data.id,calendarLink:result.data.htmlLink,meetingLink:result.data.hangoutLink};}
  async drive(userId:string,input:{approved:boolean;name:string;content:string}){this.approve(input.approved);const auth=await this.auth(userId);const {Readable}=await import('stream');const result=await google.drive({version:'v3',auth}).files.create({requestBody:{name:input.name,mimeType:'text/plain'},media:{mimeType:'text/plain',body:Readable.from([input.content])},fields:'id,name,webViewLink'});return result.data;}
  async gmail(userId:string,input:{approved:boolean;to:string;subject:string;body:string}){this.approve(input.approved);const auth=await this.auth(userId);const raw=Buffer.from([`To: ${input.to}`,`Subject: ${input.subject}`,'Content-Type: text/plain; charset=UTF-8','',input.body].join('\r\n')).toString('base64url');const result=await google.gmail({version:'v1',auth}).users.messages.send({userId:'me',requestBody:{raw}});return {messageId:result.data.id,threadId:result.data.threadId};}
}
