'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, Check, Cpu, Gauge, Layers3, ShieldCheck, Workflow } from 'lucide-react';

const metrics = [['1', 'connected operating layer'], ['24/7', 'systems that keep moving'], ['4', 'ways to run the work'], ['∞', 'room to grow into']];
const capabilities = [
  { icon: Workflow, title: 'AI workflows', copy: 'Turn repeatable work into intelligent systems that execute, remember, and improve.' },
  { icon: Layers3, title: 'Business infrastructure', copy: 'Bring cloud, VPS, edge, desktop, and mobile operations into one coherent layer.' },
  { icon: Gauge, title: 'Command visibility', copy: 'See what is moving, what is stuck, and what deserves attention before it becomes a fire.' },
  { icon: ShieldCheck, title: 'Durable control', copy: 'Build with practical security, documented decisions, and systems your team can actually own.' },
];
const deployments = [
  { label: 'FIELD OPERATIONS', title: 'HVAC intelligence', copy: 'Diagnostics, dispatch, maintenance, and customer history in one field-ready flow.', image: '/brand/wise2-brand-identity.png', href: '/hvac' },
  { label: 'CREATIVE OPERATIONS', title: 'Sound Labs', copy: 'A production environment for turning ideas into finished assets, campaigns, and culture.', image: '/brand/wise2-command-center.jpg', href: '/sound-labs' },
  { label: 'CLIENT OPERATIONS', title: 'The client OS', copy: 'A shared operating layer for keeping relationships, work, and momentum visible.', image: '/brand/wise2-hero-united.webp', href: '/platform' },
];

export function BrandEcosystemHomepage() {
  return <main className="wise-home overflow-hidden bg-[#050505] text-[#f5f7f2]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#050505]/80 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1320px] items-center justify-between px-6 lg:px-10"><Link href="/" aria-label="WISE2 home" className="leading-none"><span className="block text-[27px] font-black tracking-[-.09em]">WISE<sup className="text-sm text-[#b9ff00]">²</sup></span><span className="mt-1 block text-[9px] font-bold tracking-[.38em] text-[#b9ff00]">REAL-WORLD INTELLIGENCE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-bold tracking-[.16em] text-white/65 lg:flex"><Link href="#system" className="transition-colors hover:text-[#b9ff00]">SYSTEM</Link><Link href="#deployments" className="transition-colors hover:text-[#b9ff00]">DEPLOYMENTS</Link><Link href="/about" className="transition-colors hover:text-[#b9ff00]">ABOUT</Link><Link href="/contact" className="transition-colors hover:text-[#b9ff00]">CONTACT</Link></nav><Link href="/audit" className="inline-flex items-center gap-2 bg-[#b9ff00] px-4 py-3 text-[10px] font-black tracking-[.13em] text-black transition-transform hover:-translate-y-0.5">START WITH AN AUDIT <ArrowRight size={14} /></Link></div></header>
    <section className="relative flex min-h-[850px] items-end pt-[76px] lg:min-h-[960px]"><Image src="/brand/wise2-command-center.jpg" alt="WISE2 command center" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#050505_0%,rgba(5,5,5,.82)_31%,rgba(5,5,5,.18)_75%,#050505_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,#050505_0%,rgba(5,5,5,.05)_55%,rgba(5,5,5,.42)_100%)]" /><div className="relative mx-auto w-full max-w-[1320px] px-6 pb-20 lg:px-10 lg:pb-28"><div className="max-w-[700px]"><p className="mb-7 text-[11px] font-bold tracking-[.34em] text-[#b9ff00]">WISE² · BUSINESS OPERATING SYSTEM</p><h1 className="text-[clamp(4rem,9vw,9rem)] font-black uppercase leading-[.8] tracking-[-.075em]">Make the<br /><span className="text-[#b9ff00]">whole thing</span><br />move.</h1><p className="mt-8 max-w-[520px] text-base leading-7 text-white/75 lg:text-lg">WISE² connects the tools, people, intelligence, and infrastructure behind real businesses—so good work stops getting lost between systems.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/platform" className="inline-flex items-center gap-3 bg-[#b9ff00] px-6 py-4 text-xs font-black tracking-[.12em] text-black transition-transform hover:-translate-y-1">ENTER THE SYSTEM <ArrowRight size={16} /></Link><Link href="#system" className="inline-flex items-center gap-3 border border-white/30 bg-black/20 px-6 py-4 text-xs font-bold tracking-[.12em] text-white transition-colors hover:border-[#b9ff00] hover:text-[#b9ff00]">SEE HOW IT WORKS</Link></div></div><div className="mt-20 flex items-center gap-3 text-[10px] font-bold tracking-[.2em] text-white/50"><ArrowDown size={15} className="text-[#b9ff00]" /> SCROLL TO EXPLORE THE OPERATING LAYER</div></div></section>
    <section className="border-y border-white/10 bg-[#0b0d0b] px-6 py-12 lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([value, label]) => <div key={label} className="bg-[#0b0d0b] px-6 py-7 lg:px-8"><p className="text-4xl font-black tracking-[-.06em] text-[#b9ff00]">{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.18em] text-white/55">{label}</p></div>)}</div></section>
    <section id="system" className="mx-auto max-w-[1320px] px-6 py-28 lg:px-10 lg:py-36"><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="mb-5 text-[10px] font-bold tracking-[.32em] text-[#b9ff00]">THE WISE² DIFFERENCE</p><h2 className="max-w-2xl text-5xl font-black uppercase leading-[.86] tracking-[-.055em] md:text-7xl">One layer for the work <span className="text-white/35">between</span> the work.</h2></div><p className="max-w-lg text-base leading-7 text-white/60">Most businesses do not need more disconnected tools. They need the intelligence and operating rhythm to make the tools they already have work together.</p></div><div className="mt-16 grid gap-px bg-white/10 sm:grid-cols-2">{capabilities.map(({ icon: Icon, title, copy }, index) => <article key={title} className="group bg-[#0b0d0b] p-8 transition-colors hover:bg-[#111711] lg:p-10"><div className="flex items-start justify-between"><Icon size={27} strokeWidth={1.5} className="text-[#b9ff00]" /><span className="text-[10px] font-bold tracking-[.18em] text-white/30">0{index + 1}</span></div><h3 className="mt-16 text-2xl font-black uppercase tracking-[-.03em]">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/55">{copy}</p><div className="mt-8 h-px w-0 bg-[#b9ff00] transition-all duration-500 group-hover:w-full" /></article>)}</div></section>
    <section id="deployments" className="border-y border-white/10 bg-[#f5f7f2] px-6 py-28 text-[#050505] lg:px-10 lg:py-36"><div className="mx-auto max-w-[1320px]"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-5 text-[10px] font-bold tracking-[.32em] text-[#5c7900]">BUILT IN THE REAL WORLD</p><h2 className="max-w-2xl text-5xl font-black uppercase leading-[.86] tracking-[-.055em] md:text-7xl">Proof over promises.</h2></div><Link href="/apps" className="inline-flex items-center gap-2 text-xs font-black tracking-[.15em] text-[#5c7900]">VIEW ALL SYSTEMS <ArrowRight size={15} /></Link></div><div className="mt-16 grid gap-5 lg:grid-cols-3">{deployments.map((item) => <Link key={item.title} href={item.href} className="group block overflow-hidden bg-white"><div className="relative aspect-[4/3] overflow-hidden bg-[#101210]"><Image src={item.image} alt={item.title} fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /></div><div className="p-7"><p className="text-[10px] font-bold tracking-[.22em] text-[#5c7900]">{item.label}</p><h3 className="mt-4 text-3xl font-black uppercase tracking-[-.04em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-black/60">{item.copy}</p><span className="mt-7 inline-flex items-center gap-2 text-[10px] font-black tracking-[.16em]">EXPLORE <ArrowRight size={14} /></span></div></Link>)}</div></div></section>
    <section className="px-6 py-28 lg:px-10 lg:py-36"><div className="mx-auto grid max-w-[1320px] gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="mb-5 text-[10px] font-bold tracking-[.32em] text-[#b9ff00]">WHY WISE²</p><h2 className="max-w-3xl text-5xl font-black uppercase leading-[.86] tracking-[-.055em] md:text-7xl">Your business is already a system. <span className="text-[#b9ff00]">Make it intentional.</span></h2></div><div className="border border-white/15 bg-[#101210] p-8 lg:p-10"><Cpu className="text-[#b9ff00]" size={28} strokeWidth={1.5} /><p className="mt-10 text-xl font-bold leading-8">We build the layer that lets your people do their best work without fighting the infrastructure around them.</p><ul className="mt-8 space-y-4 text-sm text-white/60">{['Practical AI, not theater', 'Systems your team can own', 'Built for cloud, edge, and field reality'].map((item) => <li key={item} className="flex items-center gap-3"><Check size={16} className="text-[#b9ff00]" />{item}</li>)}</ul></div></div></section>
    <section className="relative px-6 py-32 text-center lg:px-10 lg:py-44"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(185,255,0,.14),transparent_48%)]" /><div className="relative mx-auto max-w-4xl"><p className="mb-6 text-[10px] font-bold tracking-[.34em] text-[#b9ff00]">START WITH THE MESSY VERSION</p><h2 className="text-6xl font-black uppercase leading-[.82] tracking-[-.07em] md:text-9xl">Make your<br /><span className="text-[#b9ff00]">move.</span></h2><p className="mx-auto mt-8 max-w-md text-sm leading-6 text-white/60">Get a clear picture of where your business is, what is slowing it down, and what to build next.</p><Link href="/audit" className="mt-10 inline-flex items-center gap-3 bg-[#b9ff00] px-7 py-4 text-xs font-black tracking-[.12em] text-black transition-transform hover:-translate-y-1">GET YOUR BUSINESS AI AUDIT <ArrowRight size={16} /></Link></div></section>
    <footer className="border-t border-white/10 px-6 py-9 lg:px-10"><div className="mx-auto flex max-w-[1320px] flex-col justify-between gap-5 text-[10px] font-bold tracking-[.14em] text-white/40 md:flex-row md:items-center"><span className="text-lg tracking-[-.08em] text-white">WISE<sup className="text-[#b9ff00]">²</sup></span><span>INTELLIGENT TOOLS FOR REAL-WORLD BUSINESSES</span><span>© 2026 WISE²</span></div></footer>
  </main>;
}
