'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, Layers3, Sparkles, Workflow } from 'lucide-react';

const characters = [
  { name: 'Darrin', role: 'Creative force', label: 'Culture + story', position: '16% center', accent: '#b9ff00' },
  { name: 'Daniel', role: 'Systems architect', label: 'Strategy + systems', position: '36% center', accent: '#d9ff4d' },
  { name: 'Ronald', role: 'Growth operator', label: 'Business + momentum', position: '58% center', accent: '#b36bff' },
  { name: 'Javon', role: 'Community builder', label: 'People + impact', position: '83% center', accent: '#8b5cf6' },
];
const pillars = [
  { icon: Workflow, title: 'One operating system', copy: 'The workflows, tools, and intelligence behind the work live in one connected command center.' },
  { icon: Layers3, title: 'Four points of view', copy: 'Strategy, creativity, growth, and community move together because the people behind them do.' },
  { icon: Sparkles, title: 'Built for the real world', copy: 'Practical AI and field-ready software that turns ambitious ideas into durable businesses.' },
];

export function BrandEcosystemHomepage() {
  return <main className="wise-home overflow-hidden bg-[#050505] text-[#f5f7f2]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#050505]/75 backdrop-blur-xl"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-6 lg:px-8"><Link href="/" className="leading-none" aria-label="WISE2 home"><span className="block text-[26px] font-black tracking-[-.08em]">WISE<sup className="text-sm text-[#b9ff00]">²</sup></span><span className="mt-1 block text-[9px] font-bold tracking-[.38em] text-[#b9ff00]">BUILT TOGETHER</span></Link><nav className="hidden items-center gap-8 text-[11px] font-bold tracking-[.16em] text-white/65 md:flex"><Link href="#people" className="transition-colors hover:text-[#b9ff00]">THE FOUR</Link><Link href="#system" className="transition-colors hover:text-[#b9ff00]">THE SYSTEM</Link><Link href="/contact" className="transition-colors hover:text-[#b9ff00]">CONTACT</Link></nav><Link href="/audit" className="border border-[#b9ff00]/60 px-4 py-2 text-[10px] font-bold tracking-[.14em] text-[#b9ff00] transition-colors hover:bg-[#b9ff00] hover:text-black">START HERE</Link></div></header>
    <section className="relative flex min-h-[760px] items-end pt-[74px] lg:min-h-[900px]"><Image src="/brand/wise2-command-center.jpg" alt="WISE2 command center with four leaders and business dashboard" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#050505_0%,rgba(5,5,5,.76)_28%,rgba(5,5,5,.12)_72%,#050505_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,#050505_0%,rgba(5,5,5,.1)_52%,rgba(5,5,5,.35)_100%)]" /><div className="relative mx-auto w-full max-w-[1240px] px-6 pb-20 lg:px-8 lg:pb-28"><div className="max-w-[650px]"><p className="mb-6 text-[11px] font-bold tracking-[.32em] text-[#b9ff00]">ATLANTA · BUSINESS OS · EST. 2024</p><h1 className="text-[clamp(3.6rem,8vw,7.7rem)] font-black uppercase leading-[.84] tracking-[-.06em]">Four minds.<br /><span className="text-[#b9ff00]">One move.</span></h1><p className="mt-7 max-w-[480px] text-base leading-7 text-white/75 lg:text-lg">WISE² connects the people, brands, and systems turning real ambition into businesses that last.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/platform" className="inline-flex items-center gap-3 bg-[#b9ff00] px-6 py-4 text-xs font-black tracking-[.12em] text-black transition-transform hover:-translate-y-1">EXPLORE THE OS <ArrowRight size={16} /></Link><Link href="#people" className="inline-flex items-center gap-3 border border-white/30 bg-black/20 px-6 py-4 text-xs font-bold tracking-[.12em] text-white transition-colors hover:border-[#b9ff00] hover:text-[#b9ff00]">MEET THE FOUR</Link></div></div><div className="mt-16 flex items-center gap-3 text-[10px] font-bold tracking-[.2em] text-white/50"><ArrowDown size={15} className="text-[#b9ff00]" /> SCROLL TO ENTER THE COMMAND CENTER</div></div></section>
    <section id="people" className="mx-auto max-w-[1240px] px-6 py-24 lg:px-8 lg:py-32"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-[10px] font-bold tracking-[.3em] text-[#b9ff00]">THE PEOPLE BEHIND THE MOTION</p><h2 className="max-w-xl text-4xl font-black uppercase leading-none tracking-[-.04em] md:text-6xl">The system starts with <span className="text-white/40">the four.</span></h2></div><p className="max-w-xs text-sm leading-6 text-white/55">Different strengths. Shared standard. A connected crew building at the intersection of business and culture.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{characters.map((character, index) => <article key={character.name} className="group relative overflow-hidden border border-white/15 bg-[#101210] transition-transform duration-300 hover:-translate-y-2"><div className="relative aspect-[4/5] overflow-hidden"><Image src="/brand/wise2-hero-united.webp" alt={`${character.name}, ${character.role}`} fill sizes="(max-width: 640px) 50vw, 25vw" className="object-cover grayscale-[.15] transition duration-500 group-hover:scale-105" style={{ objectPosition: character.position }} /><div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-transparent to-transparent" /></div><div className="absolute inset-x-0 bottom-0 p-5"><p className="mb-2 text-[10px] font-bold tracking-[.2em]" style={{ color: character.accent }}>0{index + 1} / {character.label.toUpperCase()}</p><h3 className="text-2xl font-black uppercase">{character.name}</h3><p className="mt-1 text-xs text-white/55">{character.role}</p></div></article>)}</div></section>
    <section id="system" className="border-y border-white/10 bg-[#0b0d0b] px-6 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1240px]"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="mb-4 text-[10px] font-bold tracking-[.3em] text-[#b9ff00]">THE COMMAND CENTER</p><h2 className="text-4xl font-black uppercase leading-[.9] tracking-[-.04em] md:text-6xl">Built for the work <span className="text-[#b36bff]">between</span> the ideas.</h2></div><p className="max-w-lg text-base leading-7 text-white/65">From AI workflows to client infrastructure, WISE² gives good people a better way to move from scattered effort to synchronized momentum.</p></div><div className="mt-16 grid gap-px bg-white/10 md:grid-cols-3">{pillars.map(({ icon: Icon, title, copy }) => <div key={title} className="bg-[#0b0d0b] p-8 lg:p-10"><Icon className="mb-12 text-[#b9ff00]" size={25} strokeWidth={1.5} /><h3 className="text-xl font-bold uppercase">{title}</h3><p className="mt-4 text-sm leading-6 text-white/55">{copy}</p></div>)}</div></div></section>
    <section className="relative px-6 py-28 text-center lg:py-40"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(185,255,0,.12),transparent_48%)]" /><div className="relative mx-auto max-w-3xl"><p className="mb-5 text-[10px] font-bold tracking-[.32em] text-[#b9ff00]">THE NEXT CHAPTER IS BUILT</p><h2 className="text-5xl font-black uppercase leading-[.88] tracking-[-.05em] md:text-8xl">Make your move.</h2><p className="mx-auto mt-7 max-w-md text-sm leading-6 text-white/60">Bring us the messy version. We’ll help you find the system inside it.</p><Link href="/audit" className="mt-9 inline-flex items-center gap-3 bg-[#b9ff00] px-7 py-4 text-xs font-black tracking-[.12em] text-black transition-transform hover:-translate-y-1">GET YOUR BUSINESS AI AUDIT <ArrowRight size={16} /></Link></div></section>
    <footer className="border-t border-white/10 px-6 py-8 lg:px-8"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-4 text-[10px] font-bold tracking-[.12em] text-white/40 md:flex-row"><span className="text-lg tracking-[-.08em] text-white">WISE<sup className="text-[#b9ff00]">²</sup></span><span>BUILDING EMPIRES · CHANGING CULTURE</span><span>© 2026 WISE²</span></div></footer>
  </main>;
}
