'use client';

import Link from 'next/link';
import { ArrowRight, CheckCircle2, Zap } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';

const packages = [
  { id: 'SERVICE_QUICK_START', name: 'Quick Start', price: '$99', kicker: 'Start smart', description: 'Business audit, action plan, and guided project intake.', features: ['Business audit', 'Priority action plan', 'WISE² consultation'] },
  { id: 'SERVICE_LAUNCH', name: 'Launch', price: '$299', kicker: 'Most popular', description: 'A premium one-page web presence designed to turn attention into leads.', features: ['Premium landing page', 'Mobile optimization', 'Lead capture'] },
  { id: 'SERVICE_BUSINESS_BUILD', name: 'Business Build', price: '$799+', kicker: 'Full upgrade', description: 'Website, brand, automation, and business systems working together.', features: ['Website + brand', 'AI / automation setup', 'Business system integration'] },
];

export function RevenueModeOffers() {
  const reduceMotion = useReducedMotion();
  return <section id="services" className="border-y border-white/10 bg-[#0A0E12] px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl">
    <div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#8EDBFF]">Put WISE² To Work</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">Pick the upgrade. We build the system.</h2><p className="mt-5 max-w-2xl text-base leading-8 text-[#B7C0CB]">Start with one clear outcome, then grow into the full WISE² operating system. No mystery pricing just to start the conversation.</p></div><Link href="/audit" className="inline-flex min-h-12 items-center justify-center gap-2 border border-[#8EDBFF]/40 px-5 py-3 text-sm font-bold uppercase tracking-[0.14em] text-[#DCE7EF] hover:bg-[#8EDBFF]/10">Get a Free Audit <ArrowRight size={16}/></Link></div>
    <div className="mt-12 grid gap-px overflow-hidden border border-white/10 bg-white/10 lg:grid-cols-3">{packages.map((item,index)=><motion.article key={item.id} initial={{opacity:.6,y:reduceMotion?0:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.35,delay:reduceMotion?0:index*.07}} className="flex min-h-[390px] flex-col bg-[#090C10] p-6"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8EDBFF]">{item.kicker}</p><h3 className="mt-5 text-2xl font-black">WISE² {item.name}</h3><p className="mt-3 text-4xl font-black text-[#DCE7EF]">{item.price}</p><p className="mt-5 text-sm leading-7 text-[#B7C0CB]">{item.description}</p><div className="mt-6 space-y-3">{item.features.map(feature=><div key={feature} className="flex items-center gap-2 text-sm text-[#D4DAE2]"><CheckCircle2 size={16} className="text-[#8EDBFF]"/>{feature}</div>)}</div><Link href={`/checkout?product=service&plan=${item.id}`} className="mt-auto inline-flex min-h-12 items-center justify-center gap-2 bg-[#DCE7EF] px-5 py-3 text-sm font-bold uppercase tracking-[0.12em] text-[#050607] hover:bg-white">Choose {item.name}<ArrowRight size={16}/></Link></motion.article>)}</div>
    <div className="mt-8 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2"><Link href="/checkout?product=service&plan=SERVICE_CARE" className="group bg-[#090C10] p-6 hover:bg-[#0D141A]"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8EDBFF]">Keep it sharp</p><h3 className="mt-3 text-2xl font-black">WISE² Care — $49/mo</h3><p className="mt-3 text-sm text-[#B7C0CB]">Essential ongoing site care and support.</p></div><ArrowRight className="text-[#8EDBFF] transition group-hover:translate-x-1"/></div></Link><Link href="/checkout?product=service&plan=SERVICE_GROWTH" className="group bg-[#090C10] p-6 hover:bg-[#0D141A]"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8EDBFF]">Keep growing</p><h3 className="mt-3 text-2xl font-black">WISE² Growth — $99/mo</h3><p className="mt-3 text-sm text-[#B7C0CB]">Optimization, automation support, and growth improvements.</p></div><Zap className="text-[#8EDBFF]"/></div></Link></div>
  </div></section>;
}
