'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, BarChart3, Briefcase, CheckCircle2, Gauge, MapPin, Zap } from 'lucide-react';
import { RevenueModeOffers } from '@/components/RevenueModeOffers';

const poweredBusinesses = [
  { name:'GET DOWN Pressure Washing', tagline:'Local brand to multi-city growth', metric:'3 cities', description:'Went from single location to operating across North Carolina with WISE² CRM, automation, and route management.', href:'/case-studies/get-down', icon:MapPin },
  { name:'CJAYS Auto Recon', tagline:'Detailing business at scale', metric:'$18.6K revenue', description:'Professional auto detailing app with job tracking, photo management, analytics, and customer database.', href:'/case-studies/cjays', icon:BarChart3 },
  { name:'WISE² HVAC Solutions', tagline:'Diagnostic accuracy on the jobsite', metric:'82% confidence', description:'Field technician app with real-time diagnostics, AI analysis, and smart tool connectivity.', href:'/platform', icon:Gauge },
  { name:'SenCere Creative', tagline:'Multi-brand ecommerce platform', metric:'3 brands', description:'Multiple creative brands operating from one connected system.', href:'/sencere', icon:Briefcase },
];
function RevealText({children,className=''}:{children:React.ReactNode;className?:string}){return <motion.div initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-12% 0px'}} transition={{duration:.55,ease:[.16,1,.3,1]}} className={className}>{children}</motion.div>}
export function ScrollcraftHomepage(){const reduceMotion=useReducedMotion();return <main className="overflow-hidden bg-[#050607] text-white">
<section className="relative border-b border-white/10 bg-[#050607]"><div className="absolute inset-0 bg-[linear-gradient(110deg,rgba(142,219,255,0.14),rgba(242,182,50,0.07)_34%,rgba(5,6,7,0)_66%)]"/><div className="absolute inset-0 opacity-[0.12] [background-image:linear-gradient(rgba(220,231,239,0.65)_1px,transparent_1px),linear-gradient(90deg,rgba(220,231,239,0.65)_1px,transparent_1px)] [background-size:72px_72px]"/><div className="relative mx-auto grid min-h-[calc(100vh-4rem)] max-w-7xl items-center gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.02fr_0.98fr] lg:px-8"><RevealText className="max-w-3xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.28em] text-[#8EDBFF]">Real Business. Real Results.</p><h1 className="text-5xl font-black leading-[0.93] sm:text-6xl lg:text-7xl">We build businesses that look bigger, work smarter, and sell more.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#D4DAE2] sm:text-lg">Websites, branding, apps, AI automation, and business systems—powered by WISE² and built around real service businesses.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#services" className="inline-flex min-h-12 items-center justify-center gap-2 bg-[#DCE7EF] px-5 py-3 text-sm font-bold uppercase tracking-[0.14em] text-[#050607] hover:bg-white">Start From $99 <ArrowRight size={16}/></Link><Link href="/work" className="inline-flex min-h-12 items-center justify-center gap-2 border border-white/20 bg-white/5 px-5 py-3 text-sm font-bold uppercase tracking-[0.14em] hover:border-[#8EDBFF]/70 hover:bg-[#8EDBFF]/10">See Built Work</Link></div><Link href="/audit" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#8EDBFF]">Not sure what you need? Get a free WISE² audit <ArrowRight size={14}/></Link></RevealText><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="border border-white/12 bg-[#080B0E]/92 p-5 shadow-2xl backdrop-blur-md"><div className="flex items-center justify-between border-b border-white/10 pb-4 text-[11px] uppercase tracking-[0.18em] text-[#8FA0AE]"><span>WISE² Operating System</span><span className="text-[#8EDBFF]">Real businesses powered</span></div><div className="mt-5 space-y-4">{poweredBusinesses.map(b=>{const Icon=b.icon;return <div key={b.name} className="flex items-start gap-3 border-l border-[#8EDBFF]/30 py-2 pl-4"><Icon className="mt-0.5 h-5 w-5 flex-none text-[#8EDBFF]"/><div><p className="text-sm font-bold">{b.name}</p><p className="text-[11px] text-[#8FA0AE]">{b.metric}</p></div></div>})}</div></motion.div></div></section>
<section className="border-b border-white/10 bg-[#0A0E12] px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><RevealText className="mb-12 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#8EDBFF]">Real Businesses</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Built and scaled with WISE².</h2></RevealText><div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-2">{poweredBusinesses.map((b,i)=>{const Icon=b.icon;return <motion.div key={b.name} initial={{opacity:.55}} whileInView={{opacity:1}} viewport={{once:true}} transition={{duration:.35,delay:reduceMotion?0:i*.08}}><Link href={b.href} className="group block min-h-64 bg-[#090C10] p-6 hover:bg-[#0D141A]"><Icon className="h-6 w-6 text-[#8EDBFF]"/><p className="mt-8 text-xs font-semibold uppercase tracking-[0.22em] text-[#8FA0AE]">{b.tagline}</p><h3 className="mt-3 text-2xl font-black">{b.name}</h3><p className="mt-4 text-sm leading-7 text-[#B7C0CB]">{b.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#DCE7EF]">Learn more <ArrowRight size={15}/></span></Link></motion.div>})}</div></div></section>
<section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><RevealText><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#8EDBFF]">Proof</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">Real results. Real growth.</h2></RevealText><div className="mt-10 grid gap-6 lg:grid-cols-2"><Link href="/case-studies/get-down" className="group overflow-hidden border border-white/10 bg-[#090C10]"><div className="relative aspect-[16/9] bg-black"><Image src="/uploads/daniel-real.jpg" alt="GET DOWN case study" fill className="object-cover transition duration-500 group-hover:scale-[1.03]"/></div><div className="p-6"><h3 className="text-2xl font-black">GET DOWN Pressure Washing</h3><p className="mt-3 text-sm leading-7 text-[#B7C0CB]">A service business scaled into a multi-city operation using WISE² systems.</p></div></Link><Link href="/case-studies/cjays" className="group overflow-hidden border border-white/10 bg-[#090C10]"><div className="relative aspect-[16/9] bg-black"><Image src="/wise-defense/instructors/IMG_1573.jpeg" alt="CJAYS case study" fill className="object-cover transition duration-500 group-hover:scale-[1.03]"/></div><div className="p-6"><h3 className="text-2xl font-black">CJAYS Auto Recon</h3><p className="mt-3 text-sm leading-7 text-[#B7C0CB]">Job tracking, photo capture, customer intelligence, and analytics powering real revenue.</p></div></Link></div></section>
<RevenueModeOffers />
<section className="border-b border-white/10 bg-[#050607] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><RevealText><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#8EDBFF]">Build Your Stack</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">Add what your business needs next.</h2></RevealText><div className="mt-8 grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-5">{[['Brand Refresh','$149'],['AI Lead Assistant','$199'],['Lead Automation','$149'],['AI Phone Setup','$199+'],['Extra Web Page','$75']].map(([n,p])=><div key={n} className="bg-[#090C10] p-5"><p className="text-sm font-bold">{n}</p><p className="mt-2 text-xl font-black text-[#8EDBFF]">{p}</p></div>)}</div></div></section>
<section className="border-y border-white/10 bg-[#0A0E12] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-px border border-white/10 bg-white/10 md:grid-cols-2">{[{title:'Customer Intelligence',description:'Keep customer records, job history, and service notes in one connected system.',icon:CheckCircle2},{title:'Growth Automation',description:'Follow-up, lead handling, proposals, and workflows that scale without unnecessary overhead.',icon:Zap}].map(f=>{const Icon=f.icon;return <div key={f.title} className="bg-[#090C10] p-6"><Icon className="h-6 w-6 text-[#8EDBFF]"/><h3 className="mt-6 text-2xl font-black">{f.title}</h3><p className="mt-4 text-sm leading-7 text-[#B7C0CB]">{f.description}</p></div>})}</div></div></section>
<section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-8 border border-white/10 bg-[#DCE7EF] p-8 text-[#050607] lg:grid-cols-[1fr_auto] lg:items-center"><div><Zap className="h-7 w-7"/><h2 className="mt-5 text-3xl font-black">Ready to put WISE² to work?</h2><p className="mt-3 max-w-2xl text-[#26313A]">Start with a $99 Quick Start or let us audit your business first.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/checkout?product=service&plan=SERVICE_QUICK_START" className="inline-flex min-h-12 items-center justify-center bg-[#050607] px-5 py-3 text-sm font-bold uppercase tracking-[0.12em] text-white">Start for $99</Link><Link href="/audit" className="inline-flex min-h-12 items-center justify-center border border-[#050607]/30 px-5 py-3 text-sm font-bold uppercase tracking-[0.12em]">Free Audit</Link></div></div></section>
</main>}
