'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, Bot, Command, Radio, ShieldCheck, Sparkles, Zap } from 'lucide-react';

const modules = [
  [Command, 'COMMAND CENTER', 'See the whole empire.', 'One operating view for priorities, people, projects, and the next right move.'],
  [Bot, 'AI WORKFORCE', 'Make the system think.', 'Turn repeatable work into intelligent workflows that run with you.'],
  [Radio, 'SOUNDLAB + LIVE', 'Create in public.', 'Ship audio, streams, and experiences from the same operating system.'],
  [ShieldCheck, 'FIELD + EDGE', 'Built for the real world.', 'Connect teams, devices, and job sites—even when the signal gets thin.'],
] as const;

const businesses = [
  ['WISE SHINE', 'Premium detailing', 'EMPIRE GREEN', '/platform'],
  ['PIFF CITY', 'Creative studios', 'STUDIO PURPLE', '/sencere'],
  ['WISE DEFENSE', 'Security + technology', 'GOLD THREAD', '/wise-defense'],
];

function FadeIn({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) {
  return <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .7, delay, ease: [0.16, 1, .3, 1] }} className={className}>{children}</motion.div>;
}

export function ScrollcraftHomepage() {
  const reduced = useReducedMotion();
  return <main className="wise2-home overflow-hidden bg-[#07080A] text-[#C8CCD4]">
    <section className="relative isolate min-h-[calc(100svh-4rem)] border-b border-[#14161C] bg-[#07080A]">
      <Image src="/brand/wise2-hero-united.webp" alt="WISE² founders in the command center" fill priority className="-z-10 object-cover object-center opacity-45" sizes="100vw" />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,#07080A_4%,rgba(7,8,10,.94)_34%,rgba(7,8,10,.35)_74%,#07080A_100%)]" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(0deg,#07080A,transparent_55%,rgba(7,8,10,.35))]" />
      <div className="mx-auto flex min-h-[calc(100svh-4rem)] max-w-[1440px] items-end px-6 pb-16 pt-24 sm:px-10 lg:px-16 lg:pb-24"><div className="max-w-4xl"><FadeIn><div className="mb-7 flex items-center gap-3 font-mono text-[10px] font-semibold tracking-[.28em] text-[#39FF14]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#39FF14] shadow-[0_0_16px_#39FF14]" /> ATLANTA, GA · ONLINE</div><h1 className="text-balance text-5xl font-extrabold uppercase leading-[.9] tracking-[.06em] text-[#F0F0F2] sm:text-7xl lg:text-[clamp(5rem,9vw,9rem)]">Building<br /><span className="text-[#39FF14]">empires.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-[#C8CCD4] sm:text-xl sm:leading-8">The AI-native business operating system for builders who ship, not theorize.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/platform" className="group inline-flex min-h-12 items-center justify-center gap-3 bg-[#39FF14] px-6 text-xs font-bold tracking-[.16em] text-[#07080A] transition duration-200 hover:bg-[#B4FF9F] focus:outline-none focus:ring-2 focus:ring-[#39FF14]">START BUILDING <ArrowUpRight size={17} className="transition-transform group-hover:-translate-y-0.5" /></Link><Link href="/dashboard" className="inline-flex min-h-12 items-center justify-center gap-3 border border-[#C8CCD4]/30 bg-[#07080A]/50 px-6 text-xs font-bold tracking-[.16em] text-[#E8EAEF] backdrop-blur-sm transition hover:border-[#39FF14]/70 hover:text-[#39FF14] focus:outline-none focus:ring-2 focus:ring-[#39FF14]">ENTER COMMAND CENTER</Link></div></FadeIn></div><motion.div animate={reduced ? undefined : { y: [0, -9, 0] }} transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }} className="absolute bottom-8 right-8 hidden w-64 border border-[#14161C] bg-[#0E1015]/85 p-4 backdrop-blur-md lg:block"><div className="mb-4 flex justify-between font-mono text-[9px] tracking-[.18em] text-[#6B7080]"><span>SYSTEM STATUS</span><span className="text-[#39FF14]">OPERATIONAL</span></div><div className="flex items-end gap-1.5"><div className="h-5 w-1 bg-[#39FF14]" /><div className="h-8 w-1 bg-[#39FF14]" /><div className="h-6 w-1 bg-[#39FF14]" /><div className="h-11 w-1 bg-[#39FF14]" /><div className="h-8 w-1 bg-[#39FF14]" /><div className="h-14 w-1 bg-[#39FF14]" /><span className="ml-auto font-mono text-2xl text-[#E8EAEF]">99.99%</span></div></motion.div></div>
    </section>
    <section className="border-b border-[#14161C] bg-[#07080A] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1440px]"><FadeIn className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="font-mono text-[10px] font-semibold tracking-[.24em] text-[#39FF14]">01 / THE SYSTEM</p><h2 className="mt-5 max-w-md text-3xl font-bold uppercase leading-tight tracking-[.04em] text-[#E8EAEF] sm:text-5xl">One system.<br />Infinite momentum.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-[#C8CCD4]">WISE² connects the work that usually gets fragmented: strategy, customers, field operations, creative production, and growth.</p><div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 font-mono text-[10px] tracking-[.12em] text-[#6B7080]"><span>BUILD</span><span>SELL</span><span>DEPLOY</span><span>MONITOR</span><span>AUTOMATE</span><span>RECOVER</span><span className="text-[#39FF14]">SCALE</span></div></div></FadeIn><div className="mt-16 grid gap-px border border-[#14161C] bg-[#14161C] md:grid-cols-2 lg:grid-cols-4">{modules.map(([Icon, label, title, text], i) => <FadeIn key={label} delay={i * .08}><article className="group min-h-64 bg-[#0E1015] p-7 transition-colors duration-300 hover:bg-[#12161A]"><Icon className="h-5 w-5 text-[#39FF14] transition-transform duration-300 group-hover:scale-110" strokeWidth={1.5} /><p className="mt-10 font-mono text-[9px] tracking-[.2em] text-[#6B7080]">{label}</p><h3 className="mt-3 text-xl font-bold uppercase tracking-[.03em] text-[#E8EAEF]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8F95A3]">{text}</p></article></FadeIn>)}</div></div></section>
    <section className="border-b border-[#14161C] bg-[#0E1015] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1440px]"><FadeIn><p className="font-mono text-[10px] font-semibold tracking-[.24em] text-[#39FF14]">02 / THE EMPIRE</p><div className="mt-5 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-3xl font-bold uppercase leading-tight tracking-[.04em] text-[#E8EAEF] sm:text-5xl">Three powered businesses.<br />One shared advantage.</h2><p className="max-w-sm text-sm leading-6 text-[#8F95A3]">Separate identities. Shared intelligence. A platform designed to compound what you build.</p></div></FadeIn><div className="mt-14 grid gap-4 lg:grid-cols-3">{businesses.map(([name, desc, accent, href], i) => <FadeIn key={name} delay={i * .1}><Link href={href} className="group relative min-h-72 overflow-hidden border border-[#252932] bg-[#07080A] p-7 transition duration-300 hover:-translate-y-1 hover:border-[#39FF14]/60 focus:outline-none focus:ring-2 focus:ring-[#39FF14]"><div className={`absolute right-0 top-0 h-32 w-32 rounded-full blur-3xl ${i === 1 ? 'bg-[#9333EA]/10' : i === 2 ? 'bg-[#C5A55A]/10' : 'bg-[#39FF14]/10'}`} /><p className="relative font-mono text-[9px] tracking-[.2em] text-[#6B7080]">0{i + 1} · {accent}</p><h3 className="relative mt-20 text-3xl font-extrabold uppercase tracking-[.04em] text-[#E8EAEF]">{name}</h3><p className="relative mt-2 text-sm text-[#8F95A3]">{desc}</p><ArrowUpRight className="absolute bottom-7 right-7 h-5 w-5 text-[#39FF14] transition-transform group-hover:-translate-y-1" /></Link></FadeIn>)}</div></div></section>
    <section className="px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto grid max-w-[1440px] items-center gap-12 border border-[#14161C] bg-[#0E1015] p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:p-16"><FadeIn><div className="flex items-center gap-3 font-mono text-[10px] tracking-[.2em] text-[#39FF14]"><Sparkles size={14} /> FOR BUILDERS WHO SHIP</div><h2 className="mt-6 max-w-3xl text-3xl font-bold uppercase leading-tight tracking-[.04em] text-[#F0F0F2] sm:text-5xl">Together we build<br /><span className="text-[#39FF14]">legacy.</span></h2><p className="mt-5 max-w-xl text-base leading-7 text-[#8F95A3]">Your next chapter should not require another disconnected tool. Bring the whole operation into focus.</p></FadeIn><FadeIn delay={.15}><Link href="/platform" className="inline-flex min-h-12 items-center justify-center gap-3 bg-[#39FF14] px-7 text-xs font-bold tracking-[.16em] text-[#07080A] transition hover:bg-[#B4FF9F]">EXPERIENCE WISE² <Zap size={16} /></Link></FadeIn></div></section>
  </main>;
}
