import {useEffect,useState} from 'react';import './App.css';
const cells=[
['CUSTOMERS','CRM / onboarding','https://wise2.net/customers'],
['SERVICES','delivery / projects','https://wise2.net/services'],
['AUTOMATION','agents / workflows','https://wise2.net/automation'],
['SUPPORT','triage / remote','https://wise2.net/support'],
['GROWTH','pipeline / revenue','https://wise2.net'],
['SECURITY','Shannon / authorized','#security']
];
export function App(){
 const[s,setS]=useState<any>({});const[a,setA]=useState('HERMES CORE');
 useEffect(()=>{let live=true;const f=()=>fetch('/api/status').then(x=>x.json()).then(x=>live&&setS(x)).catch(()=>{});f();const i=setInterval(f,5000);return()=>{live=false;clearInterval(i)}},[]);
 const h=s.modules?.hermes||{};const hermes=h.ready?'PRODUCTION CONNECTED':'PRODUCTION UI · DEVICE LINK PENDING';
 const open=(name:string,url:string)=>{setA(name);if(url.startsWith('http'))window.open(url,'_blank','noopener,noreferrer')};
 return <div className="hive"><header><strong>WISE<sup>2</sup></strong><span>LIVING HIVE<br/><small>SURFACE COMMAND CENTER</small></span><a className="hermesTop" href="https://wise2.net/hermes" target="_blank" rel="noreferrer">HERMES ↗</a><em>● {s.host||'WISE2-SURFACE'} · {s.tailscale_ip||'LOCAL'}</em></header><main><section className="field"><div className="aurora"/><svg viewBox="0 0 1000 650"><g>{cells.map((_,i)=><path key={i} d={'M500 325 Q '+(120+i*150)+' '+(i%2?100:550)+' '+(120+i*150)+' '+(i<3?150:500)}/>)}</g></svg><button className="core" onClick={()=>open('HERMES CORE','https://wise2.net/hermes')}><b>W²</b><span>HERMES CORE</span><small>{hermes}</small><i className={h.ready?'ready':'pending'}>{h.ready?'● LINKED':'● LOCAL STATUS'}</i></button>{cells.map((c,i)=><button key={c[0]} className={'cell c'+i} onClick={()=>open(c[0],c[2])}><b>{c[0]}</b><small>{c[1]}</small></button>)}<i className="bee one">◆</i><i className="bee two">◆</i><i className="bee three">◆</i></section><aside><h2>{a}</h2><p>{a==='HERMES CORE'?(h.note||'WISE² orchestration and device fabric.'):'Selected Hive chamber. Tap again to open its WISE² workspace.'}</p>{[['TAILSCALE',s.services?.tailscale],['DOCKER',s.services?.docker],['HERMES',h.ready?'ready':'pending'],['SHANNON',s.agents?.shannon],['BATTERY',s.battery?.capacity!=null?s.battery.capacity+'%':'--']].map((x,i)=><div className="row" key={i}><span>{x[0]}</span><b className={String(x[1]).includes('active')||x[1]==='ready'?'good':String(x[1]).includes('pending')||String(x[1]).includes('missing')?'amber':''}>{x[1]||'checking'}</b></div>)}<a href="https://wise2.net/hermes" target="_blank" rel="noreferrer">OPEN HERMES</a><a href="/system.html" target="_blank">SYSTEM DASHBOARD</a></aside></main><footer>● HIVE ONLINE · SURFACE LIVE · HERMES {h.ready?'PRODUCTION LINKED':'DEVICE LINK PENDING'} · STATUS REFRESH 5S</footer></div>}